SELECT stmc.touch_id,
       stmc.touch_mkt_channel,
       stmc.touch_landing_page,
       stmc.touch_hostname,
       stmc.touch_hostname_territory,
       stmc.utm_campaign,
       stmc.utm_medium,
       stmc.utm_source,
       stmc.utm_term,
       stmc.utm_content,
       stmc.click_id,
       stmc.sub_affiliate_name,
       stmc.affiliate,
       stmc.touch_affiliate_territory,
       stmc.awadgroupid,
       stmc.awcampaignid,
       stmc.referrer_hostname,
       stmc.referrer_medium,
       stmc.landing_page_parameters,
       se.data.CHANNEL_CATEGORY(stmc.touch_mkt_channel) AS channel
FROM se.data.scv_touch_marketing_channel stmc


SELECT
       stba.touch_id,
       stba.attributed_user_id,
       stba.stitched_identity_type,
       stba.touch_logged_in,
       stba.touch_start_tstamp,
       stba.touch_end_tstamp,
       stba.touch_duration_seconds,
       stba.touch_hostname_territory,
       stba.touch_experience,
       stba.touch_landing_page,
       stba.touch_landing_pagepath,
       stba.touch_hostname,
       stba.touch_exit_pagepath,
       stba.touch_referrer_url,
       stba.touch_event_count,
       stba.touch_has_booking,
       stba.user_ipaddress,
       stba.geo_country,
       stba.geo_city,
       stba.geo_zipcode,
       stba.geo_latitude,
       stba.geo_longitude,
       stba.geo_region_name,
       stba.useragent,
       stba.br_name,
       stba.br_family,
       stba.os_name,
       stba.os_family,
       stba.os_manufacturer,
       stba.dvce_screenwidth,
       stba.dvce_screenheight,
       se.data.PLATFORM_FROM_TOUCH_EXPERIENCE(stba.touch_experience) AS platform
FROM se.data_pii.scv_touch_basic_attributes stba