-- Create a brand-new Gen-2 warehouse
CREATE OR REPLACE WAREHOUSE my_wh
  RESOURCE_CONSTRAINT = STANDARD_GEN_2
  WAREHOUSE_SIZE      = MEDIUM;

-- Migrate an existing warehouse in-place
ALTER WAREHOUSE legacy_wh SUSPEND;
ALTER WAREHOUSE legacy_wh SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE legacy_wh RESUME;


SELECT * FROm data_vault_mvp.dwh.user_recent_activities ura;
SELECT * FROm data_vault_mvp.dwh.user_attributes ua;
SELECT * FROM se.data.se_user_attributes sua;



ALTER WAREHOUSE legacy_wh SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;


-- WAREHOUSE_NAME
-- SCV_PIPE_2XLARGE
-- SCV_PIPE_4XLARGE
-- SCV_PIPE_LARGE
-- SCV_PIPE_XLARGE


/*
ALTER WAREHOUSE legacy_wh SUSPEND;
ALTER WAREHOUSE legacy_wh SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE legacy_wh RESUME;
*/


ALTER WAREHOUSE SCV_PIPE_2XLARGE SUSPEND;
ALTER WAREHOUSE SCV_PIPE_2XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE SCV_PIPE_2XLARGE RESUME;

ALTER WAREHOUSE SCV_PIPE_4XLARGE SUSPEND;
ALTER WAREHOUSE SCV_PIPE_4XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE SCV_PIPE_4XLARGE RESUME;

ALTER WAREHOUSE SCV_PIPE_LARGE SUSPEND;
ALTER WAREHOUSE SCV_PIPE_LARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE SCV_PIPE_LARGE RESUME;

ALTER WAREHOUSE SCV_PIPE_XLARGE SUSPEND;
ALTER WAREHOUSE SCV_PIPE_XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE SCV_PIPE_XLARGE RESUME;

/*
-- testing updating an existing warehouse
CREATE OR REPLACE WAREHOUSE my_wh WAREHOUSE_SIZE = MEDIUM;

ALTER WAREHOUSE my_wh SUSPEND;
ALTER WAREHOUSE my_wh SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE my_wh RESUME;
*/
USE WAREHOUSE scv_pipe_xlarge;
SELECT * from se.data.se_user_attributes sua LIMIT 10;


ALTER WAREHOUSE DBT_PIPE_MEDIUM SUSPEND;
ALTER WAREHOUSE DBT_PIPE_MEDIUM SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE DBT_PIPE_MEDIUM RESUME;

ALTER WAREHOUSE DBT_PIPE_LARGE SUSPEND;
ALTER WAREHOUSE DBT_PIPE_LARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE DBT_PIPE_LARGE RESUME;

ALTER WAREHOUSE DBT_PIPE_XLARGE SUSPEND;
ALTER WAREHOUSE DBT_PIPE_XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE DBT_PIPE_XLARGE RESUME;

ALTER WAREHOUSE DBT_PIPE_2XLARGE SUSPEND;
ALTER WAREHOUSE DBT_PIPE_2XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE DBT_PIPE_2XLARGE RESUME;


ALTER WAREHOUSE CUSTOMER_INSIGHT_2XLARGE SUSPEND;
ALTER WAREHOUSE CUSTOMER_INSIGHT_2XLARGE SET RESOURCE_CONSTRAINT = STANDARD_GEN_2;
ALTER WAREHOUSE CUSTOMER_INSIGHT_2XLARGE RESUME;


SELECT MIN(event_tstamp) FROM se.data.scv_touched_app_installs stai

SELECT * FROM se.data.scv_touched_app_installs stai