USE WAREHOUSE PIPE_LARGE;
USE SCHEMA SCRATCH.ROBINPATELDEV35777;

SELECT GET_DDL('TABLE','SCRATCH.ROBINPATEL.MODULE_TOUCHIFICATION');


CREATE OR REPLACE TABLE MODULE_TOUCHIFICATION2 CLONE MODULE_TOUCHIFICATION;

ALTER TABLE EVENT_STREAM ADD PRIMARY KEY (EVENT_HASH);

ALTER TABLE EVENT_STREAM ADD CONSTRAINT PK_EVENT_HASH PRIMARY KEY (EVENT_HASH) NOT ENFORCED;

ALTER TABLE MODULE_TOUCHIFICATION ADD CONSTRAINT PK_EVENT_HASH PRIMARY KEY (EVENT_HASH) NOT ENFORCED;
ALTER TABLE MODULE_TOUCHIFICATION ADD CONSTRAINT FKEY_1 FOREIGN KEY (TOUCH_ID) REFERENCES MODULE_TOUCH_BASIC_ATTRIBUTES (TOUCH_ID) NOT ENFORCED;
ALTER TABLE MODULE_TOUCHIFICATION ADD CONSTRAINT FKEY_2 FOREIGN KEY (EVENT_HASH) REFERENCES EVENT_STREAM (EVENT_HASH) NOT ENFORCED;

ALTER TABLE MODULE_TOUCH_BASIC_ATTRIBUTES ADD CONSTRAINT PK_TOUCH_ID PRIMARY KEY (TOUCH_ID) NOT ENFORCED;
ALTER TABLE MODULE_TOUCHIFICATION ADD CONSTRAINT FKEY_1 FOREIGN KEY (TOUCH_ID) REFERENCES MODULE_TOUCH_BASIC_ATTRIBUTES (TOUCH_ID) NOT ENFORCED;

ALTER TABLE MODULE_TOUCH_MARKETING_CHANNEL ADD CONSTRAINT PK_TOUCH_ID PRIMARY KEY (TOUCH_ID) NOT ENFORCED;
ALTER TABLE MODULE_TOUCH_MARKETING_CHANNEL ADD CONSTRAINT FKEY_1 FOREIGN KEY (TOUCH_ID) REFERENCES MODULE_TOUCH_ATTRIBUTION (ATTRIBUTED_TOUCH_ID, ATTRIBUTION_MODEL) NOT ENFORCED;

ALTER TABLE MODULE_TOUCH_ATTRIBUTION ADD CONSTRAINT PKEY_1 PRIMARY KEY (ATTRIBUTED_TOUCH_ID, ATTRIBUTION_MODEL) NOT ENFORCED;
s

SELECT DISTINCT PRODUCT_CONFIGURATION,
                PRODUCT_LINE,
                PRODUCT_TYPE
FROM SPVS_BY_CUTTABLE_DIMENSIONS


