EXPLAIN USING TEXT
SELECT *
FROM se.data.scv_touch_basic_attributes stba
;

/*
GlobalStats:
    partitionsTotal=10162
    partitionsAssigned=10162
    bytesAssigned=189499079168
Operations:
1:0     ->Result  STBA.TOUCH_ID, SHA2(STBA.ATTRIBUTED_USER_ID), STBA.STITCHED_IDENTITY_TYPE, STBA.TOUCH_LOGGED_IN, STBA.TOUCH_START_TSTAMP, STBA.TOUCH_END_TSTAMP, STBA.TOUCH_DURATION_SECONDS, STBA.TOUCH_HOSTNAME_TERRITORY, STBA.TOUCH_EXPERIENCE, IFF(STBA.TOUCH_EXPERIENCE IN 'mobile wrap android' IN 'mobile wrap ios', 'Wrap App', IFF(STBA.TOUCH_EXPERIENCE IN 'native app ios' IN 'native app android', 'Native App', INITCAP(STBA.TOUCH_EXPERIENCE))), STBA.TOUCH_LANDING_PAGE, STBA.TOUCH_LANDING_PAGEPATH, STBA.TOUCH_HOSTNAME, STBA.TOUCH_EXIT_PAGEPATH, STBA.TOUCH_REFERRER_URL, STBA.TOUCH_SE_BRAND, STBA.TOUCH_EVENT_COUNT, STBA.TOUCH_HAS_BOOKING, STBA.IS_SE_INTERNAL_TOUCH, SHA2(STBA.USER_IPADDRESS), STBA.GEO_COUNTRY, STBA.GEO_CITY, STBA.GEO_ZIPCODE, STBA.GEO_LATITUDE, STBA.GEO_LONGITUDE, STBA.GEO_REGION_NAME, STBA.USERAGENT, STBA.BR_NAME, STBA.BR_FAMILY, STBA.OS_NAME, STBA.OS_FAMILY, STBA.OS_MANUFACTURER, STBA.DVCE_SCREENWIDTH, STBA.DVCE_SCREENHEIGHT
1:1          ->TableScan  DATA_VAULT_MVP.SINGLE_CUSTOMER_VIEW_STG.MODULE_TOUCH_BASIC_ATTRIBUTES as STBA  TOUCH_ID, ATTRIBUTED_USER_ID, STITCHED_IDENTITY_TYPE, TOUCH_LOGGED_IN, TOUCH_START_TSTAMP, TOUCH_END_TSTAMP, TOUCH_DURATION_SECONDS, TOUCH_HOSTNAME_TERRITORY, TOUCH_EXPERIENCE, TOUCH_LANDING_PAGE, TOUCH_LANDING_PAGEPATH, TOUCH_HOSTNAME, TOUCH_EXIT_PAGEPATH, TOUCH_REFERRER_URL, TOUCH_EVENT_COUNT, TOUCH_HAS_BOOKING, IS_SE_INTERNAL_TOUCH, USER_IPADDRESS, GEO_COUNTRY, GEO_CITY, GEO_ZIPCODE, GEO_LATITUDE, GEO_LONGITUDE, GEO_REGION_NAME, USERAGENT, BR_NAME, BR_FAMILY, OS_NAME, OS_FAMILY, OS_MANUFACTURER, DVCE_SCREENWIDTH, DVCE_SCREENHEIGHT, TOUCH_SE_BRAND  {partitionsTotal=10162, partitionsAssigned=10162, bytesAssigned=189499079168}

*/


EXPLAIN USING TEXT
SELECT *
FROM se.data.scv_touch_basic_attributes stba
WHERE stba.touch_start_tstamp >= CURRENT_DATE - 1;
;

/*
GlobalStats:
    partitionsTotal=10162
    partitionsAssigned=260
    bytesAssigned=4711669760
Operations:
1:0     ->Result  STBA.TOUCH_ID, SHA2(STBA.ATTRIBUTED_USER_ID), STBA.STITCHED_IDENTITY_TYPE, STBA.TOUCH_LOGGED_IN, STBA.TOUCH_START_TSTAMP, STBA.TOUCH_END_TSTAMP, STBA.TOUCH_DURATION_SECONDS, STBA.TOUCH_HOSTNAME_TERRITORY, STBA.TOUCH_EXPERIENCE, IFF(STBA.TOUCH_EXPERIENCE IN 'mobile wrap android' IN 'mobile wrap ios', 'Wrap App', IFF(STBA.TOUCH_EXPERIENCE IN 'native app ios' IN 'native app android', 'Native App', INITCAP(STBA.TOUCH_EXPERIENCE))), STBA.TOUCH_LANDING_PAGE, STBA.TOUCH_LANDING_PAGEPATH, STBA.TOUCH_HOSTNAME, STBA.TOUCH_EXIT_PAGEPATH, STBA.TOUCH_REFERRER_URL, STBA.TOUCH_SE_BRAND, STBA.TOUCH_EVENT_COUNT, STBA.TOUCH_HAS_BOOKING, STBA.IS_SE_INTERNAL_TOUCH, SHA2(STBA.USER_IPADDRESS), STBA.GEO_COUNTRY, STBA.GEO_CITY, STBA.GEO_ZIPCODE, STBA.GEO_LATITUDE, STBA.GEO_LONGITUDE, STBA.GEO_REGION_NAME, STBA.USERAGENT, STBA.BR_NAME, STBA.BR_FAMILY, STBA.OS_NAME, STBA.OS_FAMILY, STBA.OS_MANUFACTURER, STBA.DVCE_SCREENWIDTH, STBA.DVCE_SCREENHEIGHT
1:1          ->Filter  STBA.TOUCH_START_TSTAMP >= '2023-11-21 00:00:00.000000000Z'
1:2               ->TableScan  DATA_VAULT_MVP.SINGLE_CUSTOMER_VIEW_STG.MODULE_TOUCH_BASIC_ATTRIBUTES as STBA  TOUCH_ID, ATTRIBUTED_USER_ID, STITCHED_IDENTITY_TYPE, TOUCH_LOGGED_IN, TOUCH_START_TSTAMP, TOUCH_END_TSTAMP, TOUCH_DURATION_SECONDS, TOUCH_HOSTNAME_TERRITORY, TOUCH_EXPERIENCE, TOUCH_LANDING_PAGE, TOUCH_LANDING_PAGEPATH, TOUCH_HOSTNAME, TOUCH_EXIT_PAGEPATH, TOUCH_REFERRER_URL, TOUCH_EVENT_COUNT, TOUCH_HAS_BOOKING, IS_SE_INTERNAL_TOUCH, USER_IPADDRESS, GEO_COUNTRY, GEO_CITY, GEO_ZIPCODE, GEO_LATITUDE, GEO_LONGITUDE, GEO_REGION_NAME, USERAGENT, BR_NAME, BR_FAMILY, OS_NAME, OS_FAMILY, OS_MANUFACTURER, DVCE_SCREENWIDTH, DVCE_SCREENHEIGHT, TOUCH_SE_BRAND  {partitionsTotal=10162, partitionsAssigned=260, bytesAssigned=4711669760}
*/