DECLARE @BucketSize int = 2;
 
WITH cte AS
(
SELECT 
 m.MEMBER_ID,
 m.SIGN_UP_DATE,
 DATEDIFF(DAY,m.SIGN_UP_DATE,max(e.EVENT_TSTAMP)) AS DAYSOLD,
 DATEDIFF(MONTH,m.SIGN_UP_DATE,max(e.EVENT_TSTAMP)) AS MONTHSOLD,
 DATEDIFF(MONTH,m.SIGN_UP_DATE,max(e.EVENT_TSTAMP)) / @BucketSize * @BucketSize AS MONTHBUCKETFLOOR,
 (DATEDIFF(MONTH,m.SIGN_UP_DATE,max(e.EVENT_TSTAMP)) / @BucketSize + 1) * @BucketSize AS MONTHBUCKETCEILING
FROM 
 csv.Members m
JOIN 
 csv.EventsTop2000 e ON e.MEMBER_ID = m.MEMBER_ID 
GROUP BY
 m.MEMBER_ID, 
 m.SIGN_UP_DATE
),
sessioncount as
(
SELECT 
 MEMBER_ID, 
 COUNT(*) as SESSIONS
FROM 
 syn.sessions
GROUP BY 
MEMBER_ID
)

SELECT 
 CAST(MONTHBUCKETFLOOR AS VARCHAR(100)) + ' - ' + CAST(MONTHBUCKETCEILING AS VARCHAR(100)) + ' Months Oold' AS MembersAge,
 COUNT(*) AS MembersCount,
 SUM(s.SESSIONS) AS SessionsCount,
 AVG(s.SESSIONS) AS AverageEvents
FROM cte c
JOIN 
 sessioncount s ON s.MEMBER_ID = c.MEMBER_ID
GROUP BY 
 MONTHBUCKETFLOOR, 
 MONTHBUCKETCEILING;