WITH cte AS
(
SELECT 
 MEMBER_ID,
 PAGE_URLPATH,
 EVENT_TSTAMP,
 LAG(EVENT_TSTAMP,1) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_TSTAMP) AS LAST_EVENT
FROM 
 csv.EventsTop2000
),
cte2 AS
(
SELECT 
 MEMBER_ID,
 PAGE_URLPATH,
 EVENT_TSTAMP,
 CASE WHEN DATEDIFF(s, '1970-01-01', EVENT_TSTAMP) - DATEDIFF(s, '1970-01-01', LAST_EVENT) >= (60 * 30) 
	OR last_event IS NULL
 THEN 1 ELSE 0 END AS IS_NEW_SESSION
FROM 
cte
)
SELECT 
 cte2.MEMBER_ID,
 cte2.EVENT_TSTAMP,
 cte2.PAGE_URLPATH,
 SUM(IS_NEW_SESSION) OVER (PARTITION BY cte2.MEMBER_ID ORDER BY cte2.EVENT_TSTAMP) AS USER_SESSION_ID
FROM
 cte2 

