SELECT
	sends.message_id_email_hash,
	sends.email_hash,
	sends.message_id,
	sends.campaign_id,
	sends.crm_channel_type,
	sends.send_event_date,
	sends.send_event_time,
	sends.campaign_name,
	sends.splittable_email_name,
	sends.combined_email_name,
	sends.mapped_crm_date,
	sends.mapped_territory,
	sends.mapped_objective,
	sends.mapped_platform,
	sends.mapped_campaign,
	sends.mapped_theme,
	sends.mapped_segment,
	sends.email_type,
	sends.is_athena,
	sends.is_automated_campaign,
	sends.ame_calculated_campaign_name,
	sends.trading,
	sends.shiro_user_id,
	sends.current_affiliate_territory,
	opens.first_open_event_date,
	opens.first_open_event_time,
	opens.email_opens_same_day,
	opens.email_opens_1d,
	opens.email_opens_7d,
	opens.email_opens_28d,
	opens.unique_email_opens_same_day,
	opens.unique_email_opens_1d,
	opens.unique_email_opens_7d,
	opens.unique_email_opens_28d,
	clicks.first_click_event_date,
	clicks.first_click_event_time,
	clicks.email_clicks_same_day,
	clicks.email_clicks_1d,
	clicks.email_clicks_7d,
	clicks.email_clicks_28d,
	clicks.unique_email_clicks_same_day,
	clicks.unique_email_clicks_1d,
	clicks.unique_email_clicks_7d,
	clicks.unique_email_clicks_28d,
	clicks.in_app_scv_clicks_same_day,
	clicks.in_app_scv_clicks_1d,
	clicks.in_app_scv_clicks_7d,
	clicks.in_app_scv_clicks_28d,
	clicks.unique_in_app_scv_clicks_same_day,
	clicks.unique_in_app_scv_clicks_1d,
	clicks.unique_in_app_scv_clicks_7d,
	clicks.unique_in_app_scv_clicks_28d,
	unsubs.first_unsub_event_date,
	unsubs.first_unsub_event_time,
	unsubs.email_unsubs_same_day,
	unsubs.email_unsubs_1d,
	unsubs.email_unsubs_7d,
	unsubs.email_unsubs_28d,
	unsubs.email_unsubs_complaint_same_day,
	unsubs.email_unsubs_complaint_1d,
	unsubs.email_unsubs_complaint_7d,
	unsubs.email_unsubs_complaint_28d,
	unsubs.email_unsubs_email_link_same_day,
	unsubs.email_unsubs_email_link_1d,
	unsubs.email_unsubs_email_link_7d,
	unsubs.email_unsubs_email_link_28d,
	bookings.booking_id_array_lc,
	bookings.bookings_same_day_lc,
	bookings.bookings_1d_lc,
	bookings.bookings_7d_lc,
	bookings.bookings_28d_lc,
	bookings.bookings_domestic_same_day_lc,
	bookings.bookings_domestic_1d_lc,
	bookings.bookings_domestic_7d_lc,
	bookings.bookings_domestic_28d_lc,
	bookings.bookings_international_same_day_lc,
	bookings.bookings_international_1d_lc,
	bookings.bookings_international_7d_lc,
	bookings.bookings_international_28d_lc,
	bookings.bookings_hotel_same_day_lc,
	bookings.bookings_hotel_1d_lc,
	bookings.bookings_hotel_7d_lc,
	bookings.bookings_hotel_28d_lc,
	bookings.bookings_package_same_day_lc,
	bookings.bookings_package_1d_lc,
	bookings.bookings_package_7d_lc,
	bookings.bookings_package_28d_lc,
	bookings.margin_gbp_same_day_lc,
	bookings.margin_gbp_1d_lc,
	bookings.margin_gbp_7d_lc,
	bookings.margin_gbp_28d_lc,
	bookings.margin_gbp_domestic_same_day_lc,
	bookings.margin_gbp_domestic_1d_lc,
	bookings.margin_gbp_domestic_7d_lc,
	bookings.margin_gbp_domestic_28d_lc,
	bookings.margin_gbp_international_same_day_lc,
	bookings.margin_gbp_international_1d_lc,
	bookings.margin_gbp_international_7d_lc,
	bookings.margin_gbp_international_28d_lc,
	bookings.margin_gbp_hotel_same_day_lc,
	bookings.margin_gbp_hotel_1d_lc,
	bookings.margin_gbp_hotel_7d_lc,
	bookings.margin_gbp_hotel_28d_lc,
	bookings.margin_gbp_package_same_day_lc,
	bookings.margin_gbp_package_1d_lc,
	bookings.margin_gbp_package_7d_lc,
	bookings.margin_gbp_package_28d_lc,
	bookings.gross_revenue_gbp_same_day_lc,
	bookings.gross_revenue_gbp_1d_lc,
	bookings.gross_revenue_gbp_7d_lc,
	bookings.gross_revenue_gbp_28d_lc,
	bookings.gross_revenue_gbp_domestic_same_day_lc,
	bookings.gross_revenue_gbp_domestic_1d_lc,
	bookings.gross_revenue_gbp_domestic_7d_lc,
	bookings.gross_revenue_gbp_domestic_28d_lc,
	bookings.gross_revenue_gbp_international_same_day_lc,
	bookings.gross_revenue_gbp_international_1d_lc,
	bookings.gross_revenue_gbp_international_7d_lc,
	bookings.gross_revenue_gbp_international_28d_lc,
	bookings.gross_revenue_gbp_hotel_same_day_lc,
	bookings.gross_revenue_gbp_hotel_1d_lc,
	bookings.gross_revenue_gbp_hotel_7d_lc,
	bookings.gross_revenue_gbp_hotel_28d_lc,
	bookings.gross_revenue_gbp_package_same_day_lc,
	bookings.gross_revenue_gbp_package_1d_lc,
	bookings.gross_revenue_gbp_package_7d_lc,
	bookings.gross_revenue_gbp_package_28d_lc,
	bookings.booking_id_array_lnd,
	bookings.bookings_same_day_lnd,
	bookings.bookings_1d_lnd,
	bookings.bookings_7d_lnd,
	bookings.bookings_28d_lnd,
	bookings.bookings_domestic_same_day_lnd,
	bookings.bookings_domestic_1d_lnd,
	bookings.bookings_domestic_7d_lnd,
	bookings.bookings_domestic_28d_lnd,
	bookings.bookings_international_same_day_lnd,
	bookings.bookings_international_1d_lnd,
	bookings.bookings_international_7d_lnd,
	bookings.bookings_international_28d_lnd,
	bookings.bookings_hotel_same_day_lnd,
	bookings.bookings_hotel_1d_lnd,
	bookings.bookings_hotel_7d_lnd,
	bookings.bookings_hotel_28d_lnd,
	bookings.bookings_package_same_day_lnd,
	bookings.bookings_package_1d_lnd,
	bookings.bookings_package_7d_lnd,
	bookings.bookings_package_28d_lnd,
	bookings.margin_gbp_same_day_lnd,
	bookings.margin_gbp_1d_lnd,
	bookings.margin_gbp_7d_lnd,
	bookings.margin_gbp_28d_lnd,
	bookings.margin_gbp_domestic_same_day_lnd,
	bookings.margin_gbp_domestic_1d_lnd,
	bookings.margin_gbp_domestic_7d_lnd,
	bookings.margin_gbp_domestic_28d_lnd,
	bookings.margin_gbp_international_same_day_lnd,
	bookings.margin_gbp_international_1d_lnd,
	bookings.margin_gbp_international_7d_lnd,
	bookings.margin_gbp_international_28d_lnd,
	bookings.margin_gbp_hotel_same_day_lnd,
	bookings.margin_gbp_hotel_1d_lnd,
	bookings.margin_gbp_hotel_7d_lnd,
	bookings.margin_gbp_hotel_28d_lnd,
	bookings.margin_gbp_package_same_day_lnd,
	bookings.margin_gbp_package_1d_lnd,
	bookings.margin_gbp_package_7d_lnd,
	bookings.margin_gbp_package_28d_lnd,
	bookings.gross_revenue_gbp_same_day_lnd,
	bookings.gross_revenue_gbp_1d_lnd,
	bookings.gross_revenue_gbp_7d_lnd,
	bookings.gross_revenue_gbp_28d_lnd,
	bookings.gross_revenue_gbp_domestic_same_day_lnd,
	bookings.gross_revenue_gbp_domestic_1d_lnd,
	bookings.gross_revenue_gbp_domestic_7d_lnd,
	bookings.gross_revenue_gbp_domestic_28d_lnd,
	bookings.gross_revenue_gbp_international_same_day_lnd,
	bookings.gross_revenue_gbp_international_1d_lnd,
	bookings.gross_revenue_gbp_international_7d_lnd,
	bookings.gross_revenue_gbp_international_28d_lnd,
	bookings.gross_revenue_gbp_hotel_same_day_lnd,
	bookings.gross_revenue_gbp_hotel_1d_lnd,
	bookings.gross_revenue_gbp_hotel_7d_lnd,
	bookings.gross_revenue_gbp_hotel_28d_lnd,
	bookings.gross_revenue_gbp_package_same_day_lnd,
	bookings.gross_revenue_gbp_package_1d_lnd,
	bookings.gross_revenue_gbp_package_7d_lnd,
	bookings.gross_revenue_gbp_package_28d_lnd,
	bookings.los,
	bookings.los_domestic,
	bookings.los_international,
	bookings.los_hotel,
	bookings.los_package,
	spvs.spvs_same_day_lc,
	spvs.spvs_1d_lc,
	spvs.spvs_7d_lc,
	spvs.spvs_28d_lc,
	spvs.spvs_same_day_lnd,
	spvs.spvs_1d_lnd,
	spvs.spvs_7d_lnd,
	spvs.spvs_28d_lnd,
	spvs.spvs_same_day_url,
	spvs.spvs_1d_url,
	spvs.spvs_7d_url,
	spvs.spvs_28d_url
FROM data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__sends sends
	LEFT JOIN data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__opens opens
			  ON opens.message_id_email_hash = sends.message_id_email_hash
				  AND opens.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)
	LEFT JOIN data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__clicks clicks
			  ON clicks.message_id_email_hash = sends.message_id_email_hash
				  AND clicks.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)
	LEFT JOIN data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__unsubs unsubs
			  ON unsubs.message_id_email_hash = sends.message_id_email_hash
				  AND unsubs.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)

	LEFT JOIN data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__bookings bookings
			  ON bookings.message_id_email_hash = sends.message_id_email_hash
				  AND bookings.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)
	LEFT JOIN data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__spvs spvs
			  ON spvs.message_id_email_hash = sends.message_id_email_hash
				  AND spvs.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)
WHERE sends.send_event_date::DATE >= DATEADD('day', -28, '2025-07-14 04:30:00'::DATE)
;


SELECT
	message_id_email_hash,
	email_hash,
	message_id,
	campaign_id,
	crm_channel_type,
	send_event_date,
	send_event_time,
	campaign_name,
	splittable_email_name,
	combined_email_name,
	mapped_crm_date,
	mapped_territory,
	mapped_objective,
	mapped_platform,
	mapped_campaign,
	mapped_theme,
	mapped_segment,
	email_type,
	is_athena,
	is_automated_campaign,
	ame_calculated_campaign_name,
	trading,
	shiro_user_id,
	current_affiliate_territory,
	first_open_event_date,
	first_open_event_time,
	email_opens_same_day,
	email_opens_1d,
	email_opens_7d,
	email_opens_28d,
	unique_email_opens_same_day,
	unique_email_opens_1d,
	unique_email_opens_7d,
	unique_email_opens_28d,
	first_click_event_date,
	first_click_event_time,
	email_clicks_same_day,
	email_clicks_1d,
	email_clicks_7d,
	email_clicks_28d,
	unique_email_clicks_same_day,
	unique_email_clicks_1d,
	unique_email_clicks_7d,
	unique_email_clicks_28d,
	in_app_scv_clicks_same_day,
	in_app_scv_clicks_1d,
	in_app_scv_clicks_7d,
	in_app_scv_clicks_28d,
	unique_in_app_scv_clicks_same_day,
	unique_in_app_scv_clicks_1d,
	unique_in_app_scv_clicks_7d,
	unique_in_app_scv_clicks_28d,
	first_unsub_event_date,
	first_unsub_event_time,
	email_unsubs_same_day,
	email_unsubs_1d,
	email_unsubs_7d,
	email_unsubs_28d,
	email_unsubs_complaint_same_day,
	email_unsubs_complaint_1d,
	email_unsubs_complaint_7d,
	email_unsubs_complaint_28d,
	email_unsubs_email_link_same_day,
	email_unsubs_email_link_1d,
	email_unsubs_email_link_7d,
	email_unsubs_email_link_28d,
	booking_id_array_lc,
	bookings_same_day_lc,
	bookings_1d_lc,
	bookings_7d_lc,
	bookings_28d_lc,
	bookings_domestic_same_day_lc,
	bookings_domestic_1d_lc,
	bookings_domestic_7d_lc,
	bookings_domestic_28d_lc,
	bookings_international_same_day_lc,
	bookings_international_1d_lc,
	bookings_international_7d_lc,
	bookings_international_28d_lc,
	bookings_hotel_same_day_lc,
	bookings_hotel_1d_lc,
	bookings_hotel_7d_lc,
	bookings_hotel_28d_lc,
	bookings_package_same_day_lc,
	bookings_package_1d_lc,
	bookings_package_7d_lc,
	bookings_package_28d_lc,
	margin_gbp_same_day_lc,
	margin_gbp_1d_lc,
	margin_gbp_7d_lc,
	margin_gbp_28d_lc,
	margin_gbp_domestic_same_day_lc,
	margin_gbp_domestic_1d_lc,
	margin_gbp_domestic_7d_lc,
	margin_gbp_domestic_28d_lc,
	margin_gbp_international_same_day_lc,
	margin_gbp_international_1d_lc,
	margin_gbp_international_7d_lc,
	margin_gbp_international_28d_lc,
	margin_gbp_hotel_same_day_lc,
	margin_gbp_hotel_1d_lc,
	margin_gbp_hotel_7d_lc,
	margin_gbp_hotel_28d_lc,
	margin_gbp_package_same_day_lc,
	margin_gbp_package_1d_lc,
	margin_gbp_package_7d_lc,
	margin_gbp_package_28d_lc,
	gross_revenue_gbp_same_day_lc,
	gross_revenue_gbp_1d_lc,
	gross_revenue_gbp_7d_lc,
	gross_revenue_gbp_28d_lc,
	gross_revenue_gbp_domestic_same_day_lc,
	gross_revenue_gbp_domestic_1d_lc,
	gross_revenue_gbp_domestic_7d_lc,
	gross_revenue_gbp_domestic_28d_lc,
	gross_revenue_gbp_international_same_day_lc,
	gross_revenue_gbp_international_1d_lc,
	gross_revenue_gbp_international_7d_lc,
	gross_revenue_gbp_international_28d_lc,
	gross_revenue_gbp_hotel_same_day_lc,
	gross_revenue_gbp_hotel_1d_lc,
	gross_revenue_gbp_hotel_7d_lc,
	gross_revenue_gbp_hotel_28d_lc,
	gross_revenue_gbp_package_same_day_lc,
	gross_revenue_gbp_package_1d_lc,
	gross_revenue_gbp_package_7d_lc,
	gross_revenue_gbp_package_28d_lc,
	booking_id_array_lnd,
	bookings_same_day_lnd,
	bookings_1d_lnd,
	bookings_7d_lnd,
	bookings_28d_lnd,
	bookings_domestic_same_day_lnd,
	bookings_domestic_1d_lnd,
	bookings_domestic_7d_lnd,
	bookings_domestic_28d_lnd,
	bookings_international_same_day_lnd,
	bookings_international_1d_lnd,
	bookings_international_7d_lnd,
	bookings_international_28d_lnd,
	bookings_hotel_same_day_lnd,
	bookings_hotel_1d_lnd,
	bookings_hotel_7d_lnd,
	bookings_hotel_28d_lnd,
	bookings_package_same_day_lnd,
	bookings_package_1d_lnd,
	bookings_package_7d_lnd,
	bookings_package_28d_lnd,
	margin_gbp_same_day_lnd,
	margin_gbp_1d_lnd,
	margin_gbp_7d_lnd,
	margin_gbp_28d_lnd,
	margin_gbp_domestic_same_day_lnd,
	margin_gbp_domestic_1d_lnd,
	margin_gbp_domestic_7d_lnd,
	margin_gbp_domestic_28d_lnd,
	margin_gbp_international_same_day_lnd,
	margin_gbp_international_1d_lnd,
	margin_gbp_international_7d_lnd,
	margin_gbp_international_28d_lnd,
	margin_gbp_hotel_same_day_lnd,
	margin_gbp_hotel_1d_lnd,
	margin_gbp_hotel_7d_lnd,
	margin_gbp_hotel_28d_lnd,
	margin_gbp_package_same_day_lnd,
	margin_gbp_package_1d_lnd,
	margin_gbp_package_7d_lnd,
	margin_gbp_package_28d_lnd,
	gross_revenue_gbp_same_day_lnd,
	gross_revenue_gbp_1d_lnd,
	gross_revenue_gbp_7d_lnd,
	gross_revenue_gbp_28d_lnd,
	gross_revenue_gbp_domestic_same_day_lnd,
	gross_revenue_gbp_domestic_1d_lnd,
	gross_revenue_gbp_domestic_7d_lnd,
	gross_revenue_gbp_domestic_28d_lnd,
	gross_revenue_gbp_international_same_day_lnd,
	gross_revenue_gbp_international_1d_lnd,
	gross_revenue_gbp_international_7d_lnd,
	gross_revenue_gbp_international_28d_lnd,
	gross_revenue_gbp_hotel_same_day_lnd,
	gross_revenue_gbp_hotel_1d_lnd,
	gross_revenue_gbp_hotel_7d_lnd,
	gross_revenue_gbp_hotel_28d_lnd,
	gross_revenue_gbp_package_same_day_lnd,
	gross_revenue_gbp_package_1d_lnd,
	gross_revenue_gbp_package_7d_lnd,
	gross_revenue_gbp_package_28d_lnd,
	los,
	los_domestic,
	los_international,
	los_hotel,
	los_package,
	spvs_same_day_lc,
	spvs_1d_lc,
	spvs_7d_lc,
	spvs_28d_lc,
	spvs_same_day_lnd,
	spvs_1d_lnd,
	spvs_7d_lnd,
	spvs_28d_lnd,
	spvs_same_day_url,
	spvs_1d_url,
	spvs_7d_url,
	spvs_28d_url
FROM data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__migration__step01__model_data

SELECT GET_DDL('table', 'data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__migration__step01__model_data')
;

CREATE OR REPLACE TRANSIENT TABLE iterable_crm_reporting__migration__step01__model_data
(
	message_id_email_hash                        VARCHAR,
	email_hash                                   VARCHAR,
	message_id                                   VARCHAR,
	campaign_id                                  NUMBER,
	crm_channel_type                             VARCHAR,
	send_event_date                              DATE,
	send_event_time                              TIMESTAMP,
	campaign_name                                VARCHAR,
	splittable_email_name                        VARCHAR,
	combined_email_name                          VARCHAR,
	mapped_crm_date                              VARCHAR,
	mapped_territory                             VARCHAR,
	mapped_objective                             VARCHAR,
	mapped_platform                              VARCHAR,
	mapped_campaign                              VARCHAR,
	mapped_theme                                 VARCHAR,
	mapped_segment                               VARCHAR,
	email_type                                   VARCHAR,
	is_athena                                    BOOLEAN,
	is_automated_campaign                        BOOLEAN,
	ame_calculated_campaign_name                 VARCHAR,
	trading                                      VARCHAR,
	shiro_user_id                                NUMBER,
	current_affiliate_territory                  VARCHAR,
	first_open_event_date                        DATE,
	first_open_event_time                        TIMESTAMP,
	email_opens_same_day                         NUMBER,
	email_opens_1d                               NUMBER,
	email_opens_7d                               NUMBER,
	email_opens_28d                              NUMBER,
	unique_email_opens_same_day                  NUMBER,
	unique_email_opens_1d                        NUMBER,
	unique_email_opens_7d                        NUMBER,
	unique_email_opens_28d                       NUMBER,
	first_click_event_date                       DATE,
	first_click_event_time                       TIMESTAMP,
	email_clicks_same_day                        NUMBER,
	email_clicks_1d                              NUMBER,
	email_clicks_7d                              NUMBER,
	email_clicks_28d                             NUMBER,
	unique_email_clicks_same_day                 NUMBER,
	unique_email_clicks_1d                       NUMBER,
	unique_email_clicks_7d                       NUMBER,
	unique_email_clicks_28d                      NUMBER,
	in_app_scv_clicks_same_day                   NUMBER,
	in_app_scv_clicks_1d                         NUMBER,
	in_app_scv_clicks_7d                         NUMBER,
	in_app_scv_clicks_28d                        NUMBER,
	unique_in_app_scv_clicks_same_day            NUMBER,
	unique_in_app_scv_clicks_1d                  NUMBER,
	unique_in_app_scv_clicks_7d                  NUMBER,
	unique_in_app_scv_clicks_28d                 NUMBER,
	first_unsub_event_date                       DATE,
	first_unsub_event_time                       TIMESTAMP,
	email_unsubs_same_day                        NUMBER,
	email_unsubs_1d                              NUMBER,
	email_unsubs_7d                              NUMBER,
	email_unsubs_28d                             NUMBER,
	email_unsubs_complaint_same_day              NUMBER,
	email_unsubs_complaint_1d                    NUMBER,
	email_unsubs_complaint_7d                    NUMBER,
	email_unsubs_complaint_28d                   NUMBER,
	email_unsubs_email_link_same_day             NUMBER,
	email_unsubs_email_link_1d                   NUMBER,
	email_unsubs_email_link_7d                   NUMBER,
	email_unsubs_email_link_28d                  NUMBER,
	booking_id_array_lc                          ARRAY,
	bookings_same_day_lc                         NUMBER,
	bookings_1d_lc                               NUMBER,
	bookings_7d_lc                               NUMBER,
	bookings_28d_lc                              NUMBER,
	bookings_domestic_same_day_lc                NUMBER,
	bookings_domestic_1d_lc                      NUMBER,
	bookings_domestic_7d_lc                      NUMBER,
	bookings_domestic_28d_lc                     NUMBER,
	bookings_international_same_day_lc           NUMBER,
	bookings_international_1d_lc                 NUMBER,
	bookings_international_7d_lc                 NUMBER,
	bookings_international_28d_lc                NUMBER,
	bookings_hotel_same_day_lc                   NUMBER,
	bookings_hotel_1d_lc                         NUMBER,
	bookings_hotel_7d_lc                         NUMBER,
	bookings_hotel_28d_lc                        NUMBER,
	bookings_package_same_day_lc                 NUMBER,
	bookings_package_1d_lc                       NUMBER,
	bookings_package_7d_lc                       NUMBER,
	bookings_package_28d_lc                      NUMBER,
	margin_gbp_same_day_lc                       NUMBER,
	margin_gbp_1d_lc                             NUMBER,
	margin_gbp_7d_lc                             NUMBER,
	margin_gbp_28d_lc                            NUMBER,
	margin_gbp_domestic_same_day_lc              NUMBER,
	margin_gbp_domestic_1d_lc                    NUMBER,
	margin_gbp_domestic_7d_lc                    NUMBER,
	margin_gbp_domestic_28d_lc                   NUMBER,
	margin_gbp_international_same_day_lc         NUMBER,
	margin_gbp_international_1d_lc               NUMBER,
	margin_gbp_international_7d_lc               NUMBER,
	margin_gbp_international_28d_lc              NUMBER,
	margin_gbp_hotel_same_day_lc                 NUMBER,
	margin_gbp_hotel_1d_lc                       NUMBER,
	margin_gbp_hotel_7d_lc                       NUMBER,
	margin_gbp_hotel_28d_lc                      NUMBER,
	margin_gbp_package_same_day_lc               NUMBER,
	margin_gbp_package_1d_lc                     NUMBER,
	margin_gbp_package_7d_lc                     NUMBER,
	margin_gbp_package_28d_lc                    NUMBER,
	gross_revenue_gbp_same_day_lc                NUMBER,
	gross_revenue_gbp_1d_lc                      NUMBER,
	gross_revenue_gbp_7d_lc                      NUMBER,
	gross_revenue_gbp_28d_lc                     NUMBER,
	gross_revenue_gbp_domestic_same_day_lc       NUMBER,
	gross_revenue_gbp_domestic_1d_lc             NUMBER,
	gross_revenue_gbp_domestic_7d_lc             NUMBER,
	gross_revenue_gbp_domestic_28d_lc            NUMBER,
	gross_revenue_gbp_international_same_day_lc  NUMBER,
	gross_revenue_gbp_international_1d_lc        NUMBER,
	gross_revenue_gbp_international_7d_lc        NUMBER,
	gross_revenue_gbp_international_28d_lc       NUMBER,
	gross_revenue_gbp_hotel_same_day_lc          NUMBER,
	gross_revenue_gbp_hotel_1d_lc                NUMBER,
	gross_revenue_gbp_hotel_7d_lc                NUMBER,
	gross_revenue_gbp_hotel_28d_lc               NUMBER,
	gross_revenue_gbp_package_same_day_lc        NUMBER,
	gross_revenue_gbp_package_1d_lc              NUMBER,
	gross_revenue_gbp_package_7d_lc              NUMBER,
	gross_revenue_gbp_package_28d_lc             NUMBER,
	booking_id_array_lnd                         ARRAY,
	bookings_same_day_lnd                        NUMBER,
	bookings_1d_lnd                              NUMBER,
	bookings_7d_lnd                              NUMBER,
	bookings_28d_lnd                             NUMBER,
	bookings_domestic_same_day_lnd               NUMBER,
	bookings_domestic_1d_lnd                     NUMBER,
	bookings_domestic_7d_lnd                     NUMBER,
	bookings_domestic_28d_lnd                    NUMBER,
	bookings_international_same_day_lnd          NUMBER,
	bookings_international_1d_lnd                NUMBER,
	bookings_international_7d_lnd                NUMBER,
	bookings_international_28d_lnd               NUMBER,
	bookings_hotel_same_day_lnd                  NUMBER,
	bookings_hotel_1d_lnd                        NUMBER,
	bookings_hotel_7d_lnd                        NUMBER,
	bookings_hotel_28d_lnd                       NUMBER,
	bookings_package_same_day_lnd                NUMBER,
	bookings_package_1d_lnd                      NUMBER,
	bookings_package_7d_lnd                      NUMBER,
	bookings_package_28d_lnd                     NUMBER,
	margin_gbp_same_day_lnd                      NUMBER,
	margin_gbp_1d_lnd                            NUMBER,
	margin_gbp_7d_lnd                            NUMBER,
	margin_gbp_28d_lnd                           NUMBER,
	margin_gbp_domestic_same_day_lnd             NUMBER,
	margin_gbp_domestic_1d_lnd                   NUMBER,
	margin_gbp_domestic_7d_lnd                   NUMBER,
	margin_gbp_domestic_28d_lnd                  NUMBER,
	margin_gbp_international_same_day_lnd        NUMBER,
	margin_gbp_international_1d_lnd              NUMBER,
	margin_gbp_international_7d_lnd              NUMBER,
	margin_gbp_international_28d_lnd             NUMBER,
	margin_gbp_hotel_same_day_lnd                NUMBER,
	margin_gbp_hotel_1d_lnd                      NUMBER,
	margin_gbp_hotel_7d_lnd                      NUMBER,
	margin_gbp_hotel_28d_lnd                     NUMBER,
	margin_gbp_package_same_day_lnd              NUMBER,
	margin_gbp_package_1d_lnd                    NUMBER,
	margin_gbp_package_7d_lnd                    NUMBER,
	margin_gbp_package_28d_lnd                   NUMBER,
	gross_revenue_gbp_same_day_lnd               NUMBER,
	gross_revenue_gbp_1d_lnd                     NUMBER,
	gross_revenue_gbp_7d_lnd                     NUMBER,
	gross_revenue_gbp_28d_lnd                    NUMBER,
	gross_revenue_gbp_domestic_same_day_lnd      NUMBER,
	gross_revenue_gbp_domestic_1d_lnd            NUMBER,
	gross_revenue_gbp_domestic_7d_lnd            NUMBER,
	gross_revenue_gbp_domestic_28d_lnd           NUMBER,
	gross_revenue_gbp_international_same_day_lnd NUMBER,
	gross_revenue_gbp_international_1d_lnd       NUMBER,
	gross_revenue_gbp_international_7d_lnd       NUMBER,
	gross_revenue_gbp_international_28d_lnd      NUMBER,
	gross_revenue_gbp_hotel_same_day_lnd         NUMBER,
	gross_revenue_gbp_hotel_1d_lnd               NUMBER,
	gross_revenue_gbp_hotel_7d_lnd               NUMBER,
	gross_revenue_gbp_hotel_28d_lnd              NUMBER,
	gross_revenue_gbp_package_same_day_lnd       NUMBER,
	gross_revenue_gbp_package_1d_lnd             NUMBER,
	gross_revenue_gbp_package_7d_lnd             NUMBER,
	gross_revenue_gbp_package_28d_lnd            NUMBER,
	los                                          NUMBER,
	los_domestic                                 NUMBER,
	los_international                            NUMBER,
	los_hotel                                    NUMBER,
	los_package                                  NUMBER,
	spvs_same_day_lc                             NUMBER,
	spvs_1d_lc                                   NUMBER,
	spvs_7d_lc                                   NUMBER,
	spvs_28d_lc                                  NUMBER,
	spvs_same_day_lnd                            NUMBER,
	spvs_1d_lnd                                  NUMBER,
	spvs_7d_lnd                                  NUMBER,
	spvs_28d_lnd                                 NUMBER,
	spvs_same_day_url                            NUMBER,
	spvs_1d_url                                  NUMBER,
	spvs_7d_url                                  NUMBER,
	spvs_28d_url                                 NUMBER,
)
;

SELECT
	COUNT(*)
FROM data_vault_mvp.dwh.iterable_crm_reporting icr
WHERE send_event_date >= '2021-11-03'
;
-- 10,160,217,863
SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__migration
;
-- 10,171,549,792

SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__sends icrs


DROP TABLE data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__migration
;

self_describing_task --include 'biapp/task_catalogue/dv/dwh/email/crm_reporting/iterable/iterable_crm_reporting__migration.py'  --method 'run' --start '2021-11-03 00:00:00' --end '2021-11-03 00:00:00'


biapp/
task_catalogue/
dv/
dwh/
EMAIL/
crm_reporting/
iterable/
iterable_crm_reporting__migration.py


CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.user_attributes
	CLONE data_vault_mvp.dwh.user_attributes
;

CREATE SCHEMA IF NOT EXISTS dbt_dev_robin.bi_customer_insight
;

CREATE OR REPLACE TRANSIENT TABLE dbt_dev_robin.bi_customer_insight.ci_rfv_segments_historical_weekly
	CLONE dbt.bi_customer_insight.ci_rfv_segments_historical_weekly
;

SELECT
	schedule_tstamp,
	run_tstamp,
	operation_id,
	created_at,
	updated_at,
	message_id_email_hash,
	email_hash,
	message_id,
	campaign_id,
	crm_channel_type,
	send_event_date,
	send_event_time,
	campaign_name,
	splittable_email_name,
	combined_email_name,
	mapped_crm_date,
	mapped_territory,
	mapped_objective,
	mapped_platform,
	mapped_campaign,
	mapped_theme,
	mapped_segment,
	email_type,
	is_athena,
	is_automated_campaign,
	ame_calculated_campaign_name,
	trading,
	shiro_user_id,
	current_affiliate_territory,
	rfv_segment,
	rfv_lifecycle,
	rfv_segment_calc,
	rfv_lifecycle_calc,
	first_open_event_date,
	first_open_event_time,
	email_opens_same_day,
	email_opens_1d,
	email_opens_7d,
	email_opens_28d,
	unique_email_opens_same_day,
	unique_email_opens_1d,
	unique_email_opens_7d,
	unique_email_opens_28d,
	first_click_event_date,
	first_click_event_time,
	email_clicks_same_day,
	email_clicks_1d,
	email_clicks_7d,
	email_clicks_28d,
	unique_email_clicks_same_day,
	unique_email_clicks_1d,
	unique_email_clicks_7d,
	unique_email_clicks_28d,
	in_app_scv_clicks_same_day,
	in_app_scv_clicks_1d,
	in_app_scv_clicks_7d,
	in_app_scv_clicks_28d,
	unique_in_app_scv_clicks_same_day,
	unique_in_app_scv_clicks_1d,
	unique_in_app_scv_clicks_7d,
	unique_in_app_scv_clicks_28d,
	first_unsub_event_date,
	first_unsub_event_time,
	email_unsubs_same_day,
	email_unsubs_1d,
	email_unsubs_7d,
	email_unsubs_28d,
	email_unsubs_complaint_same_day,
	email_unsubs_complaint_1d,
	email_unsubs_complaint_7d,
	email_unsubs_complaint_28d,
	email_unsubs_email_link_same_day,
	email_unsubs_email_link_1d,
	email_unsubs_email_link_7d,
	email_unsubs_email_link_28d,
	booking_id_array_lc,
	bookings_same_day_lc,
	bookings_1d_lc,
	bookings_7d_lc,
	bookings_28d_lc,
	bookings_domestic_same_day_lc,
	bookings_domestic_1d_lc,
	bookings_domestic_7d_lc,
	bookings_domestic_28d_lc,
	bookings_international_same_day_lc,
	bookings_international_1d_lc,
	bookings_international_7d_lc,
	bookings_international_28d_lc,
	bookings_hotel_same_day_lc,
	bookings_hotel_1d_lc,
	bookings_hotel_7d_lc,
	bookings_hotel_28d_lc,
	bookings_package_same_day_lc,
	bookings_package_1d_lc,
	bookings_package_7d_lc,
	bookings_package_28d_lc,
	margin_gbp_same_day_lc,
	margin_gbp_1d_lc,
	margin_gbp_7d_lc,
	margin_gbp_28d_lc,
	margin_gbp_domestic_same_day_lc,
	margin_gbp_domestic_1d_lc,
	margin_gbp_domestic_7d_lc,
	margin_gbp_domestic_28d_lc,
	margin_gbp_international_same_day_lc,
	margin_gbp_international_1d_lc,
	margin_gbp_international_7d_lc,
	margin_gbp_international_28d_lc,
	margin_gbp_hotel_same_day_lc,
	margin_gbp_hotel_1d_lc,
	margin_gbp_hotel_7d_lc,
	margin_gbp_hotel_28d_lc,
	margin_gbp_package_same_day_lc,
	margin_gbp_package_1d_lc,
	margin_gbp_package_7d_lc,
	margin_gbp_package_28d_lc,
	gross_revenue_gbp_same_day_lc,
	gross_revenue_gbp_1d_lc,
	gross_revenue_gbp_7d_lc,
	gross_revenue_gbp_28d_lc,
	gross_revenue_gbp_domestic_same_day_lc,
	gross_revenue_gbp_domestic_1d_lc,
	gross_revenue_gbp_domestic_7d_lc,
	gross_revenue_gbp_domestic_28d_lc,
	gross_revenue_gbp_international_same_day_lc,
	gross_revenue_gbp_international_1d_lc,
	gross_revenue_gbp_international_7d_lc,
	gross_revenue_gbp_international_28d_lc,
	gross_revenue_gbp_hotel_same_day_lc,
	gross_revenue_gbp_hotel_1d_lc,
	gross_revenue_gbp_hotel_7d_lc,
	gross_revenue_gbp_hotel_28d_lc,
	gross_revenue_gbp_package_same_day_lc,
	gross_revenue_gbp_package_1d_lc,
	gross_revenue_gbp_package_7d_lc,
	gross_revenue_gbp_package_28d_lc,
	booking_id_array_lnd,
	bookings_same_day_lnd,
	bookings_1d_lnd,
	bookings_7d_lnd,
	bookings_28d_lnd,
	bookings_domestic_same_day_lnd,
	bookings_domestic_1d_lnd,
	bookings_domestic_7d_lnd,
	bookings_domestic_28d_lnd,
	bookings_international_same_day_lnd,
	bookings_international_1d_lnd,
	bookings_international_7d_lnd,
	bookings_international_28d_lnd,
	bookings_hotel_same_day_lnd,
	bookings_hotel_1d_lnd,
	bookings_hotel_7d_lnd,
	bookings_hotel_28d_lnd,
	bookings_package_same_day_lnd,
	bookings_package_1d_lnd,
	bookings_package_7d_lnd,
	bookings_package_28d_lnd,
	margin_gbp_same_day_lnd,
	margin_gbp_1d_lnd,
	margin_gbp_7d_lnd,
	margin_gbp_28d_lnd,
	margin_gbp_domestic_same_day_lnd,
	margin_gbp_domestic_1d_lnd,
	margin_gbp_domestic_7d_lnd,
	margin_gbp_domestic_28d_lnd,
	margin_gbp_international_same_day_lnd,
	margin_gbp_international_1d_lnd,
	margin_gbp_international_7d_lnd,
	margin_gbp_international_28d_lnd,
	margin_gbp_hotel_same_day_lnd,
	margin_gbp_hotel_1d_lnd,
	margin_gbp_hotel_7d_lnd,
	margin_gbp_hotel_28d_lnd,
	margin_gbp_package_same_day_lnd,
	margin_gbp_package_1d_lnd,
	margin_gbp_package_7d_lnd,
	margin_gbp_package_28d_lnd,
	gross_revenue_gbp_same_day_lnd,
	gross_revenue_gbp_1d_lnd,
	gross_revenue_gbp_7d_lnd,
	gross_revenue_gbp_28d_lnd,
	gross_revenue_gbp_domestic_same_day_lnd,
	gross_revenue_gbp_domestic_1d_lnd,
	gross_revenue_gbp_domestic_7d_lnd,
	gross_revenue_gbp_domestic_28d_lnd,
	gross_revenue_gbp_international_same_day_lnd,
	gross_revenue_gbp_international_1d_lnd,
	gross_revenue_gbp_international_7d_lnd,
	gross_revenue_gbp_international_28d_lnd,
	gross_revenue_gbp_hotel_same_day_lnd,
	gross_revenue_gbp_hotel_1d_lnd,
	gross_revenue_gbp_hotel_7d_lnd,
	gross_revenue_gbp_hotel_28d_lnd,
	gross_revenue_gbp_package_same_day_lnd,
	gross_revenue_gbp_package_1d_lnd,
	gross_revenue_gbp_package_7d_lnd,
	gross_revenue_gbp_package_28d_lnd,
	los,
	los_domestic,
	los_international,
	los_hotel,
	los_package,
	spvs_same_day_lc,
	spvs_1d_lc,
	spvs_7d_lc,
	spvs_28d_lc,
	spvs_same_day_lnd,
	spvs_1d_lnd,
	spvs_7d_lnd,
	spvs_28d_lnd,
	spvs_same_day_url,
	spvs_1d_url,
	spvs_7d_url,
	spvs_28d_url
FROM data_vault_mvp_dev_robin.dwh.iterable_crm_reporting__migration
WHERE ITERABLE_CRM_REPORTING__MIGRATION.bookings_7d_lc > 0