ALTER TABLE snowplow.atomic.event
    ALTER app_id SET DATA TYPE VARCHAR,
        platform SET DATA TYPE VARCHAR,
        event SET DATA TYPE VARCHAR,
        event_id SET DATA TYPE VARCHAR,
        name_tracker SET DATA TYPE VARCHAR,
        v_tracker SET DATA TYPE VARCHAR,
        v_collector SET DATA TYPE VARCHAR,
        v_etl SET DATA TYPE VARCHAR,
        user_id SET DATA TYPE VARCHAR,
        user_ipaddress SET DATA TYPE VARCHAR,
        user_fingerprint SET DATA TYPE VARCHAR,
        domain_userid SET DATA TYPE VARCHAR,
        network_userid SET DATA TYPE VARCHAR,
        geo_country SET DATA TYPE VARCHAR,
        geo_region SET DATA TYPE VARCHAR,
        geo_city SET DATA TYPE VARCHAR,
        geo_zipcode SET DATA TYPE VARCHAR,
        geo_region_name SET DATA TYPE VARCHAR,
        ip_isp SET DATA TYPE VARCHAR,
        ip_organization SET DATA TYPE VARCHAR,
        ip_domain SET DATA TYPE VARCHAR,
        ip_netspeed SET DATA TYPE VARCHAR,
        page_url SET DATA TYPE VARCHAR,
        page_title SET DATA TYPE VARCHAR,
        page_referrer SET DATA TYPE VARCHAR,
        page_urlscheme SET DATA TYPE VARCHAR,
        page_urlhost SET DATA TYPE VARCHAR,
        page_urlpath SET DATA TYPE VARCHAR,
        page_urlquery SET DATA TYPE VARCHAR,
        page_urlfragment SET DATA TYPE VARCHAR,
        refr_urlscheme SET DATA TYPE VARCHAR,
        refr_urlhost SET DATA TYPE VARCHAR,
        refr_urlpath SET DATA TYPE VARCHAR,
        refr_urlquery SET DATA TYPE VARCHAR,
        refr_urlfragment SET DATA TYPE VARCHAR,
        refr_medium SET DATA TYPE VARCHAR,
        refr_source SET DATA TYPE VARCHAR,
        refr_term SET DATA TYPE VARCHAR,
        mkt_medium SET DATA TYPE VARCHAR,
        mkt_source SET DATA TYPE VARCHAR,
        mkt_term SET DATA TYPE VARCHAR,
        mkt_content SET DATA TYPE VARCHAR,
        mkt_campaign SET DATA TYPE VARCHAR,
        se_category SET DATA TYPE VARCHAR,
        se_action SET DATA TYPE VARCHAR,
        se_label SET DATA TYPE VARCHAR,
        se_property SET DATA TYPE VARCHAR,
        tr_orderid SET DATA TYPE VARCHAR,
        tr_affiliation SET DATA TYPE VARCHAR,
        tr_city SET DATA TYPE VARCHAR,
        tr_state SET DATA TYPE VARCHAR,
        tr_country SET DATA TYPE VARCHAR,
        ti_orderid SET DATA TYPE VARCHAR,
        ti_sku SET DATA TYPE VARCHAR,
        ti_name SET DATA TYPE VARCHAR,
        ti_category SET DATA TYPE VARCHAR,
        useragent SET DATA TYPE VARCHAR,
        br_name SET DATA TYPE VARCHAR,
        br_family SET DATA TYPE VARCHAR,
        br_version SET DATA TYPE VARCHAR,
        br_type SET DATA TYPE VARCHAR,
        br_renderengine SET DATA TYPE VARCHAR,
        br_lang SET DATA TYPE VARCHAR,
        br_colordepth SET DATA TYPE VARCHAR,
        os_name SET DATA TYPE VARCHAR,
        os_family SET DATA TYPE VARCHAR,
        os_manufacturer SET DATA TYPE VARCHAR,
        os_timezone SET DATA TYPE VARCHAR,
        dvce_type SET DATA TYPE VARCHAR,
        doc_charset SET DATA TYPE VARCHAR,
        tr_currency SET DATA TYPE VARCHAR,
        ti_currency SET DATA TYPE VARCHAR,
        base_currency SET DATA TYPE VARCHAR,
        geo_timezone SET DATA TYPE VARCHAR,
        mkt_clickid SET DATA TYPE VARCHAR,
        mkt_network SET DATA TYPE VARCHAR,
        etl_tags SET DATA TYPE VARCHAR,
        refr_domain_userid SET DATA TYPE VARCHAR,
        domain_sessionid SET DATA TYPE VARCHAR,
        event_vendor SET DATA TYPE VARCHAR,
        event_name SET DATA TYPE VARCHAR,
        event_format SET DATA TYPE VARCHAR,
        event_version SET DATA TYPE VARCHAR,
        event_fingerprint SET DATA TYPE VARCHAR;

CREATE OR REPLACE TABLE scratch.robinpatel.events clone snowplow.atomic.events;

SELECT * FROM scratch.robinpatel.events LIMIT 10;

DROP TABLE scratch.robinpatel.events;


CREATE OR REPLACE TABLE hygiene_vault_mvp_dev_robin.snowplow.event_stream CLONE hygiene_vault_mvp.snowplow.event_stream;

self_describing_task --include 'staging/hygiene/snowplow/events'  --method 'run' --start '2020-04-13 00:00:00' --end '2020-04-13 00:00:00'

SELECT * FROM hygiene_vault_mvp_dev_robin.snowplow.event_stream WHERE created_at > '2020-04-14 13:00:00';

DROP TABLE hygiene_vault_mvp_dev_robin.snowplow.event_stream;