SELECT
	profile_activity.shiro_user_id,
	profile_activity.row_hash,
	profile_activity.current_affiliate_territory,
	profile_activity.membership_account_status,
	profile_activity.daily_opt_in,
	profile_activity.weekly_opt_in,
	profile_activity.user_has_ranks,
	profile_activity.last_email_open_tstamp,
	profile_activity.last_email_click_tstamp,
	profile_activity.last_sale_pageview_tstamp,
	profile_activity.last_purchase_tstamp,
	profile_activity.penultimate_spv_tstamp,
	profile_activity.days_between_penultimate_and_current_spv,
	profile_activity.most_recent_non_purchase_activity,
	profile_activity.daily_spv_deals,
	profile_activity.weekly_spv_deals,
	profile_activity.monthly_spv_deals,
	profile_activity.sales_page_views_last_7_days,
	profile_activity.sales_page_views_last_14_days,
	profile_activity.sales_page_views_last_30_days,
	profile_activity.sales_page_views_last_60_days,
	profile_activity.segment_name,
	profile_activity.athena_segment_name,
	profile_activity.signup_tstamp,
	profile_activity.last_session_end_tstamp,
	profile_activity.last_app_session_end_tstamp,
	profile_activity.user_last_updated_tstamp,
	profile_activity.profile_last_updated_tstamp,
	profile_activity.last_voucher_purchase_tstamp,
	profile_activity.latest_cash_credit_expiration_tstamp,
	profile_activity.user_inactivity_flag,
	profile_activity.user_to_be_deleted_on,
	profile_activity.sale_tags_last_7_days,
	profile_activity.sale_tags_last_30_days,
	profile_activity.sale_tags_last_60_days,
	profile_activity.last_booking_review_object,
	profile_activity.number_of_reviews,
	profile_activity.nps_score,
	profile_activity.user_search_one_to_nine_results,
	profile_activity.user_search_greater_than_nine_results,
	profile_activity.is_user_search_equal,
	profile_activity.sessions_last_1_days,
	profile_activity.sessions_last_7_days,
	profile_activity.sessions_last_14_days,
	profile_activity.avg_spvs_per_session_last_1_7_14_days,
	profile_activity.num_sale_page_views_1_days,
	profile_activity.num_sale_page_views_7_days,
	profile_activity.num_sale_page_views_14_days,
	profile_activity.num_sale_page_views_30_days,
	profile_activity.num_sales_page_views_last_60_days,
	profile_activity.num_intl_sale_page_views_7_days,
	profile_activity.num_intl_sale_page_views_14_days,
	profile_activity.num_intl_sale_page_views_30_days,
	profile_activity.num_domestic_sale_page_views_7_days,
	profile_activity.num_domestic_sale_page_views_14_days,
	profile_activity.num_domestic_sale_page_views_30_days,
	profile_activity.top_5_sale_page_views_last_1_days,
	profile_activity.top_5_sale_page_views_last_7_days,
	profile_activity.top_5_sale_page_views_last_14_days,
	profile_activity.top_2_most_popular_tag_by_sale_page_views,
	profile_activity.top_2_tag_spvs_last_7_days,
	profile_activity.top_2_tag_spvs_last_14_days,
	profile_activity.top_2_tag_spvs_last_30_days,
	profile_activity.top_2_tag_spvs_last_60_days,
	profile_activity.user_favorites_array,
	profile_activity.user_wishlist_array,
	profile_activity.user_has_credit,
	profile_activity.user_credit_total,
	profile_activity.user_credit_array,
	profile_activity.recency_frequency_value,
	profile_activity.ab_test_member_history_array,
	profile_activity.sunday_deals,
	profile_activity.mention_me_object,
	profile_activity.is_legitimate_interest_eligible
FROM data_vault_mvp.dwh.iterable__user_profile_activity profile_activity
;

TRUNCATE data_vault_mvp_dev_robin.dwh.iterable__user_profile_activity_snapshot
;

USE WAREHOUSE pipe_2xlarge
;


CREATE TABLE IF NOT EXISTS data_vault_mvp_dev_robin.dwh.iterable__user_profile_activity_snapshot (
-- (lineage) metadata for the current job
	schedule_tstamp TIMESTAMP,
	run_tstamp TIMESTAMP,
	operation_id VARCHAR,
	created_at TIMESTAMP,
	updated_at TIMESTAMP,

	view_date DATE,
	shiro_user_id INT,
	row_hash VARCHAR,
	current_affiliate_territory VARCHAR,
	membership_account_status VARCHAR,
	daily_opt_in BOOLEAN,
	weekly_opt_in BOOLEAN,
	user_has_ranks BOOLEAN,
	last_email_open_tstamp TIMESTAMP,
	last_email_click_tstamp TIMESTAMP,
	last_sale_pageview_tstamp TIMESTAMP,
	last_purchase_tstamp TIMESTAMP,
	penultimate_spv_tstamp TIMESTAMP,
	days_between_penultimate_and_current_spv NUMBER,
	most_recent_non_purchase_activity TIMESTAMP,
	daily_spv_deals ARRAY,
	weekly_spv_deals ARRAY,
	monthly_spv_deals ARRAY,
	sales_page_views_last_7_days ARRAY,
	sales_page_views_last_14_days ARRAY,
	sales_page_views_last_30_days ARRAY,
	sales_page_views_last_60_days ARRAY,
	segment_name VARCHAR,
	athena_segment_name VARCHAR,
	signup_tstamp TIMESTAMP,
	last_session_end_tstamp TIMESTAMP,
	last_app_session_end_tstamp TIMESTAMP,
	user_last_updated_tstamp TIMESTAMP,
	profile_last_updated_tstamp TIMESTAMP,
	last_voucher_purchase_tstamp TIMESTAMP,
	latest_cash_credit_expiration_tstamp TIMESTAMP,
	user_inactivity_flag BOOLEAN,
	user_to_be_deleted_on DATE,
	sale_tags_last_7_days ARRAY,
	sale_tags_last_30_days ARRAY,
	sale_tags_last_60_days ARRAY,
	last_booking_review_object OBJECT,
	number_of_reviews NUMBER,
	nps_score DECIMAL (13,4),
	user_search_one_to_nine_results OBJECT,
	user_search_greater_than_nine_results OBJECT,
	is_user_search_equal BOOLEAN,
	sessions_last_1_days NUMBER,
	sessions_last_7_days NUMBER,
	sessions_last_14_days NUMBER,
	avg_spvs_per_session_last_1_7_14_days ARRAY,
	num_sale_page_views_1_days NUMBER,
	num_sale_page_views_7_days NUMBER,
	num_sale_page_views_14_days NUMBER,
	num_sale_page_views_30_days NUMBER,
	num_sales_page_views_last_60_days NUMBER,
	num_intl_sale_page_views_7_days NUMBER,
	num_intl_sale_page_views_14_days NUMBER,
	num_intl_sale_page_views_30_days NUMBER,
	num_domestic_sale_page_views_7_days NUMBER,
	num_domestic_sale_page_views_14_days NUMBER,
	num_domestic_sale_page_views_30_days NUMBER,
	top_5_sale_page_views_last_1_days ARRAY,
	top_5_sale_page_views_last_7_days ARRAY,
	top_5_sale_page_views_last_14_days ARRAY,
	top_2_most_popular_tag_by_sale_page_views ARRAY,
	top_2_tag_spvs_last_7_days ARRAY,
	top_2_tag_spvs_last_14_days ARRAY,
	top_2_tag_spvs_last_30_days ARRAY,
	top_2_tag_spvs_last_60_days ARRAY,
	user_favorites_array ARRAY,
	user_wishlist_array ARRAY,
	user_has_credit BOOLEAN,
	user_credit_total OBJECT,
	user_credit_array ARRAY,
	recency_frequency_value OBJECT,
	ab_test_member_history_array ARRAY,
	sunday_deals OBJECT,
	mention_me_object OBJECT,
	is_legitimate_interest_eligible BOOLEAN,
	CONSTRAINT pk_iterable__user_profile_activity_snapshot
		PRIMARY KEY (
			shiro_user_id,
			view_date
		)
	)
;

INSERT INTO data_vault_mvp_dev_robin.dwh.iterable__user_profile_activity_snapshot
SELECT
	CURRENT_TIMESTAMP                         AS schedule_tstamp,
	CURRENT_TIMESTAMP                         AS run_tstamp,
	'manual backfill from CI snapshot in dbt' AS operation_id,
	CURRENT_TIMESTAMP                         AS created_at,
	CURRENT_TIMESTAMP                         AS updated_at,

	model_run_date                            AS view_date,
	shiro_user_id                             AS shiro_user_id,
	row_hash                                  AS row_hash,
	current_affiliate_territory               AS current_affiliate_territory,
	membership_account_status                 AS membership_account_status,
	daily_opt_in                              AS daily_opt_in,
	weekly_opt_in                             AS weekly_opt_in,
	user_has_ranks                            AS user_has_ranks,
	last_email_open_tstamp                    AS last_email_open_tstamp,
	last_email_click_tstamp                   AS last_email_click_tstamp,
	last_sale_pageview_tstamp                 AS last_sale_pageview_tstamp,
	last_purchase_tstamp                      AS last_purchase_tstamp,
	penultimate_spv_tstamp                    AS penultimate_spv_tstamp,
	days_between_penultimate_and_current_spv  AS days_between_penultimate_and_current_spv,
	most_recent_non_purchase_activity         AS most_recent_non_purchase_activity,
	daily_spv_deals                           AS daily_spv_deals,
	weekly_spv_deals                          AS weekly_spv_deals,
	NULL                                      AS monthly_spv_deals,
	sales_page_views_last_7_days              AS sales_page_views_last_7_days,
	sales_page_views_last_14_days             AS sales_page_views_last_14_days,
	sales_page_views_last_30_days             AS sales_page_views_last_30_days,
	sales_page_views_last_60_days             AS sales_page_views_last_60_days,
	segment_name                              AS segment_name,
	athena_segment_name                       AS athena_segment_name,
	NULL                                      AS signup_tstamp,
	NULL                                      AS last_session_end_tstamp,
	NULL                                      AS last_app_session_end_tstamp,
	NULL                                      AS user_last_updated_tstamp,
	NULL                                      AS profile_last_updated_tstamp,
	NULL                                      AS last_voucher_purchase_tstamp,
	NULL                                      AS latest_cash_credit_expiration_tstamp,
	NULL                                      AS user_inactivity_flag,
	NULL                                      AS user_to_be_deleted_on,
	sale_tags_last_7_days                     AS sale_tags_last_7_days,
	sale_tags_last_30_days                    AS sale_tags_last_30_days,
	sale_tags_last_60_days                    AS sale_tags_last_60_days,
	last_booking_review_object                AS last_booking_review_object,
	number_of_reviews                         AS number_of_reviews,
	nps_score                                 AS nps_score,
	user_search_one_to_nine_results           AS user_search_one_to_nine_results,
	user_search_greater_than_nine_results     AS user_search_greater_than_nine_results,
	is_user_search_equal                      AS is_user_search_equal,
	sessions_last_1_days                      AS sessions_last_1_days,
	sessions_last_7_days                      AS sessions_last_7_days,
	sessions_last_14_days                     AS sessions_last_14_days,
	avg_spvs_per_session_last_1_7_14_days     AS avg_spvs_per_session_last_1_7_14_days,
	num_sale_page_views_1_days                AS num_sale_page_views_1_days,
	num_sale_page_views_7_days                AS num_sale_page_views_7_days,
	num_sale_page_views_14_days               AS num_sale_page_views_14_days,
	num_sale_page_views_30_days               AS num_sale_page_views_30_days,
	num_sales_page_views_last_60_days         AS num_sales_page_views_last_60_days,
	num_intl_sale_page_views_7_days           AS num_intl_sale_page_views_7_days,
	num_intl_sale_page_views_14_days          AS num_intl_sale_page_views_14_days,
	num_intl_sale_page_views_30_days          AS num_intl_sale_page_views_30_days,
	num_domestic_sale_page_views_7_days       AS num_domestic_sale_page_views_7_days,
	num_domestic_sale_page_views_14_days      AS num_domestic_sale_page_views_14_days,
	num_domestic_sale_page_views_30_days      AS num_domestic_sale_page_views_30_days,
	top_5_sale_page_views_last_1_days         AS top_5_sale_page_views_last_1_days,
	top_5_sale_page_views_last_7_days         AS top_5_sale_page_views_last_7_days,
	top_5_sale_page_views_last_14_days        AS top_5_sale_page_views_last_14_days,
	top_2_most_popular_tag_by_sale_page_views AS top_2_most_popular_tag_by_sale_page_views,
	top_2_tag_spvs_last_7_days                AS top_2_tag_spvs_last_7_days,
	top_2_tag_spvs_last_14_days               AS top_2_tag_spvs_last_14_days,
	top_2_tag_spvs_last_30_days               AS top_2_tag_spvs_last_30_days,
	top_2_tag_spvs_last_60_days               AS top_2_tag_spvs_last_60_days,
	user_favorites_array                      AS user_favorites_array,
	user_wishlist_array                       AS user_wishlist_array,
	NULL                                      AS user_has_credit,
	NULL                                      AS user_credit_total,
	NULL                                      AS user_credit_array,
	NULL                                      AS recency_frequency_value,
	NULL                                      AS ab_test_member_history_array,
	NULL                                      AS sunday_deals,
	NULL                                      AS mention_me_object,
	NULL                                      AS is_legitimate_interest_eligible
FROM dbt.bi_customer_insight.ci_iterable_user_profile_activity_daily;


USE ROLE pipelinerunner;

CREATE TABLE IF NOT EXISTS data_vault_mvp.dwh.iterable__user_profile_activity_snapshot (
-- (lineage) metadata for the current job
	schedule_tstamp TIMESTAMP,
	run_tstamp TIMESTAMP,
	operation_id VARCHAR,
	created_at TIMESTAMP,
	updated_at TIMESTAMP,

	view_date DATE,
	shiro_user_id INT,
	row_hash VARCHAR,
	current_affiliate_territory VARCHAR,
	membership_account_status VARCHAR,
	daily_opt_in BOOLEAN,
	weekly_opt_in BOOLEAN,
	user_has_ranks BOOLEAN,
	last_email_open_tstamp TIMESTAMP,
	last_email_click_tstamp TIMESTAMP,
	last_sale_pageview_tstamp TIMESTAMP,
	last_purchase_tstamp TIMESTAMP,
	penultimate_spv_tstamp TIMESTAMP,
	days_between_penultimate_and_current_spv NUMBER,
	most_recent_non_purchase_activity TIMESTAMP,
	daily_spv_deals ARRAY,
	weekly_spv_deals ARRAY,
	monthly_spv_deals ARRAY,
	sales_page_views_last_7_days ARRAY,
	sales_page_views_last_14_days ARRAY,
	sales_page_views_last_30_days ARRAY,
	sales_page_views_last_60_days ARRAY,
	segment_name VARCHAR,
	athena_segment_name VARCHAR,
	signup_tstamp TIMESTAMP,
	last_session_end_tstamp TIMESTAMP,
	last_app_session_end_tstamp TIMESTAMP,
	user_last_updated_tstamp TIMESTAMP,
	profile_last_updated_tstamp TIMESTAMP,
	last_voucher_purchase_tstamp TIMESTAMP,
	latest_cash_credit_expiration_tstamp TIMESTAMP,
	user_inactivity_flag BOOLEAN,
	user_to_be_deleted_on DATE,
	sale_tags_last_7_days ARRAY,
	sale_tags_last_30_days ARRAY,
	sale_tags_last_60_days ARRAY,
	last_booking_review_object OBJECT,
	number_of_reviews NUMBER,
	nps_score DECIMAL (13,4),
	user_search_one_to_nine_results OBJECT,
	user_search_greater_than_nine_results OBJECT,
	is_user_search_equal BOOLEAN,
	sessions_last_1_days NUMBER,
	sessions_last_7_days NUMBER,
	sessions_last_14_days NUMBER,
	avg_spvs_per_session_last_1_7_14_days ARRAY,
	num_sale_page_views_1_days NUMBER,
	num_sale_page_views_7_days NUMBER,
	num_sale_page_views_14_days NUMBER,
	num_sale_page_views_30_days NUMBER,
	num_sales_page_views_last_60_days NUMBER,
	num_intl_sale_page_views_7_days NUMBER,
	num_intl_sale_page_views_14_days NUMBER,
	num_intl_sale_page_views_30_days NUMBER,
	num_domestic_sale_page_views_7_days NUMBER,
	num_domestic_sale_page_views_14_days NUMBER,
	num_domestic_sale_page_views_30_days NUMBER,
	top_5_sale_page_views_last_1_days ARRAY,
	top_5_sale_page_views_last_7_days ARRAY,
	top_5_sale_page_views_last_14_days ARRAY,
	top_2_most_popular_tag_by_sale_page_views ARRAY,
	top_2_tag_spvs_last_7_days ARRAY,
	top_2_tag_spvs_last_14_days ARRAY,
	top_2_tag_spvs_last_30_days ARRAY,
	top_2_tag_spvs_last_60_days ARRAY,
	user_favorites_array ARRAY,
	user_wishlist_array ARRAY,
	user_has_credit BOOLEAN,
	user_credit_total OBJECT,
	user_credit_array ARRAY,
	recency_frequency_value OBJECT,
	ab_test_member_history_array ARRAY,
	sunday_deals OBJECT,
	mention_me_object OBJECT,
	is_legitimate_interest_eligible BOOLEAN,
	CONSTRAINT pk_iterable__user_profile_activity_snapshot
		PRIMARY KEY (
			shiro_user_id,
			view_date
		)
	)
;

USE WAREHOUSE pipe_2xlarge;

INSERT INTO data_vault_mvp.dwh.iterable__user_profile_activity_snapshot
SELECT
	CURRENT_TIMESTAMP                         AS schedule_tstamp,
	CURRENT_TIMESTAMP                         AS run_tstamp,
	'manual backfill from CI snapshot in dbt' AS operation_id,
	CURRENT_TIMESTAMP                         AS created_at,
	CURRENT_TIMESTAMP                         AS updated_at,

	model_run_date                            AS view_date,
	shiro_user_id                             AS shiro_user_id,
	row_hash                                  AS row_hash,
	current_affiliate_territory               AS current_affiliate_territory,
	membership_account_status                 AS membership_account_status,
	daily_opt_in                              AS daily_opt_in,
	weekly_opt_in                             AS weekly_opt_in,
	user_has_ranks                            AS user_has_ranks,
	last_email_open_tstamp                    AS last_email_open_tstamp,
	last_email_click_tstamp                   AS last_email_click_tstamp,
	last_sale_pageview_tstamp                 AS last_sale_pageview_tstamp,
	last_purchase_tstamp                      AS last_purchase_tstamp,
	penultimate_spv_tstamp                    AS penultimate_spv_tstamp,
	days_between_penultimate_and_current_spv  AS days_between_penultimate_and_current_spv,
	most_recent_non_purchase_activity         AS most_recent_non_purchase_activity,
	daily_spv_deals                           AS daily_spv_deals,
	weekly_spv_deals                          AS weekly_spv_deals,
	NULL                                      AS monthly_spv_deals,
	sales_page_views_last_7_days              AS sales_page_views_last_7_days,
	sales_page_views_last_14_days             AS sales_page_views_last_14_days,
	sales_page_views_last_30_days             AS sales_page_views_last_30_days,
	sales_page_views_last_60_days             AS sales_page_views_last_60_days,
	segment_name                              AS segment_name,
	athena_segment_name                       AS athena_segment_name,
	NULL                                      AS signup_tstamp,
	NULL                                      AS last_session_end_tstamp,
	NULL                                      AS last_app_session_end_tstamp,
	NULL                                      AS user_last_updated_tstamp,
	NULL                                      AS profile_last_updated_tstamp,
	NULL                                      AS last_voucher_purchase_tstamp,
	NULL                                      AS latest_cash_credit_expiration_tstamp,
	NULL                                      AS user_inactivity_flag,
	NULL                                      AS user_to_be_deleted_on,
	sale_tags_last_7_days                     AS sale_tags_last_7_days,
	sale_tags_last_30_days                    AS sale_tags_last_30_days,
	sale_tags_last_60_days                    AS sale_tags_last_60_days,
	last_booking_review_object                AS last_booking_review_object,
	number_of_reviews                         AS number_of_reviews,
	nps_score                                 AS nps_score,
	user_search_one_to_nine_results           AS user_search_one_to_nine_results,
	user_search_greater_than_nine_results     AS user_search_greater_than_nine_results,
	is_user_search_equal                      AS is_user_search_equal,
	sessions_last_1_days                      AS sessions_last_1_days,
	sessions_last_7_days                      AS sessions_last_7_days,
	sessions_last_14_days                     AS sessions_last_14_days,
	avg_spvs_per_session_last_1_7_14_days     AS avg_spvs_per_session_last_1_7_14_days,
	num_sale_page_views_1_days                AS num_sale_page_views_1_days,
	num_sale_page_views_7_days                AS num_sale_page_views_7_days,
	num_sale_page_views_14_days               AS num_sale_page_views_14_days,
	num_sale_page_views_30_days               AS num_sale_page_views_30_days,
	num_sales_page_views_last_60_days         AS num_sales_page_views_last_60_days,
	num_intl_sale_page_views_7_days           AS num_intl_sale_page_views_7_days,
	num_intl_sale_page_views_14_days          AS num_intl_sale_page_views_14_days,
	num_intl_sale_page_views_30_days          AS num_intl_sale_page_views_30_days,
	num_domestic_sale_page_views_7_days       AS num_domestic_sale_page_views_7_days,
	num_domestic_sale_page_views_14_days      AS num_domestic_sale_page_views_14_days,
	num_domestic_sale_page_views_30_days      AS num_domestic_sale_page_views_30_days,
	top_5_sale_page_views_last_1_days         AS top_5_sale_page_views_last_1_days,
	top_5_sale_page_views_last_7_days         AS top_5_sale_page_views_last_7_days,
	top_5_sale_page_views_last_14_days        AS top_5_sale_page_views_last_14_days,
	top_2_most_popular_tag_by_sale_page_views AS top_2_most_popular_tag_by_sale_page_views,
	top_2_tag_spvs_last_7_days                AS top_2_tag_spvs_last_7_days,
	top_2_tag_spvs_last_14_days               AS top_2_tag_spvs_last_14_days,
	top_2_tag_spvs_last_30_days               AS top_2_tag_spvs_last_30_days,
	top_2_tag_spvs_last_60_days               AS top_2_tag_spvs_last_60_days,
	user_favorites_array                      AS user_favorites_array,
	user_wishlist_array                       AS user_wishlist_array,
	NULL                                      AS user_has_credit,
	NULL                                      AS user_credit_total,
	NULL                                      AS user_credit_array,
	NULL                                      AS recency_frequency_value,
	NULL                                      AS ab_test_member_history_array,
	NULL                                      AS sunday_deals,
	NULL                                      AS mention_me_object,
	NULL                                      AS is_legitimate_interest_eligible
FROM dbt.bi_customer_insight.ci_iterable_user_profile_activity_daily;


GRANT SELECT ON TABLE data_vault_mvp.dwh.iterable__user_profile_activity_snapshot TO ROLE data_team_basic;