USE WAREHOUSE pipe_xlarge
;

SELECT
	COUNT(*)
FROM data_vault_mvp.dwh.se_booking_snapshot
;

-- current production row count of se_booking_snapshot: 78,939,481,190


-- create a smaller last 10 days version of se_booking_snapshot to develop on
CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking_snapshot AS
SELECT *
FROM data_vault_mvp.dwh.se_booking_snapshot sbs
WHERE sbs.view_date >= CURRENT_DATE - 10
;

-- create a backup of trimmed table so we can compare against deletes
CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking_snapshot_backup CLONE data_vault_mvp_dev_robin.dwh.se_booking_snapshot
;

WITH
	input_data AS (
		-- temp cte to aid with development times
		SELECT *
		FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
		WHERE se_booking_snapshot.booking_id
				  IN (
					  '6846177', -- abandoned example
					  'A15118823', -- complete example
					  'A8017799' -- refunded example
				  )
	)
		,
	create_row_hash AS (
		-- introduce a row_hash column to aid with merge and deletion
		SELECT
			schedule_tstamp,
			run_tstamp,
			operation_id,
			created_at,
			updated_at,
			HASH(booking_id,
				 transaction_id,
				 unique_transaction_reference,
				 last_updated,
				 last_updated_booking_summary,
				 last_updated_bookings,
				 last_updated_reservations,
				 territory,
				 booking_status,
				 currency,
				 booking_completed_date,
				 booking_completed_timestamp,
				 booking_created_date,
				 booking_created_timestamp,
				 cs_agent_booking,
				 shiro_user_id,
				 affiliate_user_id,
				 device_platform,
				 cc_rate_to_gbp,
				 cc_rate_to_sc,
				 gbp_rate_to_sc,
				 reservation_exchange_rate_cc_to_sc,
				 gross_revenue_cc,
				 customer_total_price_cc,
				 gross_booking_value_cc,
				 margin_gross_of_toms_cc,
				 margin_gross_of_toms_cc__o,
				 margin_current_cc,
				 vat_on_commission_cc,
				 commission_ex_vat_cc,
				 booking_fee_cc,
				 booking_fee_net_rate_cc,
				 payment_surcharge_cc,
				 payment_surcharge_net_rate_cc,
				 insurance_commission_cc,
				 insurance_price_cc,
				 credits_used_cc,
				 cash_credits_used_cc,
				 non_cash_credits_used_cc,
				 total_custom_tax_cc,
				 atol_fee_cc,
				 total_sell_rate_cc,
				 flight_amount_cc,
				 flight_commission_cc,
				 flight_commission_cc__o,
				 flight_only_price_cc,
				 flight_only_price_cc__o,
				 flight_vat_on_commission_cc,
				 flight_buy_rate_cc,
				 flight_buy_rate_cc__o,
				 total_received_from_user_cc,
				 gross_revenue_gbp,
				 gross_revenue_gbp_constant_currency,
				 customer_total_price_gbp,
				 customer_total_price_gbp_constant_currency,
				 gross_booking_value_gbp,
				 margin_gross_of_toms_gbp,
				 margin_gross_of_toms_gbp__o,
				 margin_gross_of_toms_gbp_constant_currency,
				 margin_current_gbp,
				 margin_current_gbp_constant_currency,
				 vat_on_commission_gbp,
				 commission_ex_vat_gbp,
				 booking_fee_gbp,
				 booking_fee_net_rate_gbp,
				 payment_surcharge_gbp,
				 payment_surcharge_net_rate_gbp,
				 insurance_commission_gbp,
				 insurance_price_gbp,
				 credits_used_gbp,
				 cash_credits_used_gbp,
				 non_cash_credits_used_gbp,
				 total_custom_tax_gbp,
				 atol_fee_gbp,
				 total_sell_rate_gbp,
				 flight_amount_gbp,
				 flight_commission_gbp,
				 flight_commission_gbp__o,
				 flight_only_price_gbp,
				 flight_only_price_gbp__o,
				 flight_vat_on_commission_gbp,
				 flight_buy_rate_gbp,
				 flight_buy_rate_gbp__o,
				 total_received_from_user_gbp,
				 gross_revenue_sc,
				 customer_total_price_sc,
				 gross_booking_value_sc,
				 margin_gross_of_toms_sc,
				 margin_gross_of_toms_sc__o,
				 vat_on_commission_sc,
				 commission_ex_vat_sc,
				 booking_fee_sc,
				 booking_fee_net_rate_sc,
				 payment_surcharge_sc,
				 payment_surcharge_net_rate_sc,
				 insurance_commission_sc,
				 insurance_price_sc,
				 credits_used_sc,
				 cash_credits_used_sc,
				 non_cash_credits_used_sc,
				 total_custom_tax_sc,
				 atol_fee_sc,
				 total_sell_rate_sc,
				 flight_amount_sc,
				 flight_commission_sc,
				 flight_commission_sc__o,
				 flight_only_price_sc,
				 flight_only_price_sc__o,
				 flight_vat_on_commission_sc,
				 flight_buy_rate_sc,
				 flight_buy_rate_sc__o,
				 total_received_from_user_sc,
				 gross_revenue_eur_constant_currency,
				 margin_gross_of_toms_eur_constant_currency,
				 margin_current_eur_constant_currency,
				 mongo_total_price_sc,
				 mongo_commission_ex_vat_sc,
				 mongo_vat_on_commission_sc,
				 mongo_total_custom_tax_sc,
				 sale_id,
				 sale_name,
				 sale_base_currency,
				 sale_dimension,
				 offer_id,
				 offer_name,
				 offer_rate_code,
				 offer_travel_date_length,
				 board_basis,
				 room_name,
				 bundle_id,
				 check_in_date,
				 check_out_date,
				 booking_lead_time_days,
				 booking_type,
				 no_nights,
				 rooms,
				 room_nights,
				 adult_guests,
				 child_guests,
				 infant_guests,
				 top_discount,
				 sale_product,
				 sale_type,
				 booking_category,
				 has_flights,
				 inbound_flight_arrival_timestamp,
				 inbound_flight_arrival_date,
				 outbound_flight_departure_timestamp,
				 outbound_flight_departure_date,
				 departure_airport_code,
				 sale_closest_airport_code,
				 flight_carrier,
				 flight_invoice_number,
				 flight_supplier_name,
				 flight_supplier_reference,
				 flight_change_type_list,
				 flight_change_reason_list,
				 flight_adjustment_last_updated,
				 price_per_night,
				 price_per_person_per_night,
				 supplier_name,
				 provider_name,
				 rebooked,
				 date_of_rebooking,
				 original_check_in_date,
				 original_check_out_date,
				 voucher_stay_by_date,
				 is_new_model_booking,
				 is_staff_booking,
				 staff_booking_discount_type,
				 affiliate_id,
				 affiliate,
				 affiliate_domain,
				 agent_id,
				 payment_id,
				 hold_id,
				 insurance_provider,
				 payment_type,
				 zero_deposit_flag,
				 supplier_to_user_currency_exchange_rate_id,
				 is_affiliate_booking,
				 vcc_reference,
				 se_brand,
				 accommodation_channel_manager,
				 booking_present_in_chiasma,
				 refund_type,
				 total_refunded_cc,
				 total_refunded_gbp,
				 total_refunded_sc,
				 cancellation_date,
				 cancellation_tstamp,
				 cancellation_fault,
				 cancellation_reason,
				 cancellation_refund_channel,
				 cancellation_status,
				 cancellation_requested_by,
				 cancellation_requested_by_domain,
				 cancellation_payment_provider_refund_status,
				 cancellation_mode,
				 cancellation_policy_id,
				 is_cancellable,
				 cancellation_policy_number_of_days,
				 cancellation_policy_percentage) AS row_hash,
			view_date,
			booking_id,
			transaction_id,
			unique_transaction_reference,
			last_updated,
			last_updated_booking_summary,
			last_updated_bookings,
			last_updated_reservations,
			territory,
			booking_status,
			currency,
			booking_completed_date,
			booking_completed_timestamp,
			booking_created_date,
			booking_created_timestamp,
			cs_agent_booking,
			shiro_user_id,
			affiliate_user_id,
			device_platform,
			cc_rate_to_gbp,
			cc_rate_to_sc,
			gbp_rate_to_sc,
			reservation_exchange_rate_cc_to_sc,
			gross_revenue_cc,
			customer_total_price_cc,
			gross_booking_value_cc,
			margin_gross_of_toms_cc,
			margin_gross_of_toms_cc__o,
			margin_current_cc,
			vat_on_commission_cc,
			commission_ex_vat_cc,
			booking_fee_cc,
			booking_fee_net_rate_cc,
			payment_surcharge_cc,
			payment_surcharge_net_rate_cc,
			insurance_commission_cc,
			insurance_price_cc,
			credits_used_cc,
			cash_credits_used_cc,
			non_cash_credits_used_cc,
			total_custom_tax_cc,
			atol_fee_cc,
			total_sell_rate_cc,
			flight_amount_cc,
			flight_commission_cc,
			flight_commission_cc__o,
			flight_only_price_cc,
			flight_only_price_cc__o,
			flight_vat_on_commission_cc,
			flight_buy_rate_cc,
			flight_buy_rate_cc__o,
			total_received_from_user_cc,
			gross_revenue_gbp,
			gross_revenue_gbp_constant_currency,
			customer_total_price_gbp,
			customer_total_price_gbp_constant_currency,
			gross_booking_value_gbp,
			margin_gross_of_toms_gbp,
			margin_gross_of_toms_gbp__o,
			margin_gross_of_toms_gbp_constant_currency,
			margin_current_gbp,
			margin_current_gbp_constant_currency,
			vat_on_commission_gbp,
			commission_ex_vat_gbp,
			booking_fee_gbp,
			booking_fee_net_rate_gbp,
			payment_surcharge_gbp,
			payment_surcharge_net_rate_gbp,
			insurance_commission_gbp,
			insurance_price_gbp,
			credits_used_gbp,
			cash_credits_used_gbp,
			non_cash_credits_used_gbp,
			total_custom_tax_gbp,
			atol_fee_gbp,
			total_sell_rate_gbp,
			flight_amount_gbp,
			flight_commission_gbp,
			flight_commission_gbp__o,
			flight_only_price_gbp,
			flight_only_price_gbp__o,
			flight_vat_on_commission_gbp,
			flight_buy_rate_gbp,
			flight_buy_rate_gbp__o,
			total_received_from_user_gbp,
			gross_revenue_sc,
			customer_total_price_sc,
			gross_booking_value_sc,
			margin_gross_of_toms_sc,
			margin_gross_of_toms_sc__o,
			vat_on_commission_sc,
			commission_ex_vat_sc,
			booking_fee_sc,
			booking_fee_net_rate_sc,
			payment_surcharge_sc,
			payment_surcharge_net_rate_sc,
			insurance_commission_sc,
			insurance_price_sc,
			credits_used_sc,
			cash_credits_used_sc,
			non_cash_credits_used_sc,
			total_custom_tax_sc,
			atol_fee_sc,
			total_sell_rate_sc,
			flight_amount_sc,
			flight_commission_sc,
			flight_commission_sc__o,
			flight_only_price_sc,
			flight_only_price_sc__o,
			flight_vat_on_commission_sc,
			flight_buy_rate_sc,
			flight_buy_rate_sc__o,
			total_received_from_user_sc,
			gross_revenue_eur_constant_currency,
			margin_gross_of_toms_eur_constant_currency,
			margin_current_eur_constant_currency,
			mongo_total_price_sc,
			mongo_commission_ex_vat_sc,
			mongo_vat_on_commission_sc,
			mongo_total_custom_tax_sc,
			sale_id,
			sale_name,
			sale_base_currency,
			sale_dimension,
			offer_id,
			offer_name,
			offer_rate_code,
			offer_travel_date_length,
			board_basis,
			room_name,
			bundle_id,
			check_in_date,
			check_out_date,
			booking_lead_time_days,
			booking_type,
			no_nights,
			rooms,
			room_nights,
			adult_guests,
			child_guests,
			infant_guests,
			top_discount,
			sale_product,
			sale_type,
			booking_category,
			has_flights,
			inbound_flight_arrival_timestamp,
			inbound_flight_arrival_date,
			outbound_flight_departure_timestamp,
			outbound_flight_departure_date,
			departure_airport_code,
			sale_closest_airport_code,
			flight_carrier,
			flight_invoice_number,
			flight_supplier_name,
			flight_supplier_reference,
			flight_change_type_list,
			flight_change_reason_list,
			flight_adjustment_last_updated,
			price_per_night,
			price_per_person_per_night,
			supplier_name,
			provider_name,
			rebooked,
			date_of_rebooking,
			original_check_in_date,
			original_check_out_date,
			voucher_stay_by_date,
			is_new_model_booking,
			is_staff_booking,
			staff_booking_discount_type,
			affiliate_id,
			affiliate,
			affiliate_domain,
			agent_id,
			payment_id,
			hold_id,
			insurance_provider,
			payment_type,
			zero_deposit_flag,
			supplier_to_user_currency_exchange_rate_id,
			is_affiliate_booking,
			vcc_reference,
			se_brand,
			accommodation_channel_manager,
			booking_present_in_chiasma,
			refund_type,
			total_refunded_cc,
			total_refunded_gbp,
			total_refunded_sc,
			cancellation_date,
			cancellation_tstamp,
			cancellation_fault,
			cancellation_reason,
			cancellation_refund_channel,
			cancellation_status,
			cancellation_requested_by,
			cancellation_requested_by_domain,
			cancellation_payment_provider_refund_status,
			cancellation_mode,
			cancellation_policy_id,
			is_cancellable,
			cancellation_policy_number_of_days,
			cancellation_policy_percentage
		FROM input_data AS se_booking_snapshot --  data_vault_mvp_dev_robin.dwh.se_booking_snapshot
	)
SELECT *
FROM create_row_hash
QUALIFY
	ROW_NUMBER() OVER (PARTITION BY create_row_hash.booking_id, create_row_hash.row_hash ORDER BY create_row_hash.view_date ASC) =
	1
;

USE WAREHOUSE pipe_xlarge
;

INSERT INTO data_vault_mvp_dev_robin.dwh.se_booking_changelog
WITH
	create_row_hash AS (
		-- introduce a row_hash column to aid with merge and deletion
		SELECT
			schedule_tstamp,
			run_tstamp,
			operation_id,
			created_at,
			updated_at,
			view_date,
			HASH(booking_id,
				 transaction_id,
				 unique_transaction_reference,
				 last_updated,
				 last_updated_booking_summary,
				 last_updated_bookings,
				 last_updated_reservations,
				 territory,
				 booking_status,
				 currency,
				 booking_completed_date,
				 booking_completed_timestamp,
				 booking_created_date,
				 booking_created_timestamp,
				 cs_agent_booking,
				 shiro_user_id,
				 affiliate_user_id,
				 device_platform,
				 cc_rate_to_gbp,
				 cc_rate_to_sc,
				 gbp_rate_to_sc,
				 reservation_exchange_rate_cc_to_sc,
				 gross_revenue_cc,
				 customer_total_price_cc,
				 gross_booking_value_cc,
				 margin_gross_of_toms_cc,
				 margin_gross_of_toms_cc__o,
				 margin_current_cc,
				 vat_on_commission_cc,
				 commission_ex_vat_cc,
				 booking_fee_cc,
				 booking_fee_net_rate_cc,
				 payment_surcharge_cc,
				 payment_surcharge_net_rate_cc,
				 insurance_commission_cc,
				 insurance_price_cc,
				 credits_used_cc,
				 cash_credits_used_cc,
				 non_cash_credits_used_cc,
				 total_custom_tax_cc,
				 atol_fee_cc,
				 total_sell_rate_cc,
				 flight_amount_cc,
				 flight_commission_cc,
				 flight_commission_cc__o,
				 flight_only_price_cc,
				 flight_only_price_cc__o,
				 flight_vat_on_commission_cc,
				 flight_buy_rate_cc,
				 flight_buy_rate_cc__o,
				 total_received_from_user_cc,
				 gross_revenue_gbp,
				 gross_revenue_gbp_constant_currency,
				 customer_total_price_gbp,
				 customer_total_price_gbp_constant_currency,
				 gross_booking_value_gbp,
				 margin_gross_of_toms_gbp,
				 margin_gross_of_toms_gbp__o,
				 margin_gross_of_toms_gbp_constant_currency,
				 margin_current_gbp,
				 margin_current_gbp_constant_currency,
				 vat_on_commission_gbp,
				 commission_ex_vat_gbp,
				 booking_fee_gbp,
				 booking_fee_net_rate_gbp,
				 payment_surcharge_gbp,
				 payment_surcharge_net_rate_gbp,
				 insurance_commission_gbp,
				 insurance_price_gbp,
				 credits_used_gbp,
				 cash_credits_used_gbp,
				 non_cash_credits_used_gbp,
				 total_custom_tax_gbp,
				 atol_fee_gbp,
				 total_sell_rate_gbp,
				 flight_amount_gbp,
				 flight_commission_gbp,
				 flight_commission_gbp__o,
				 flight_only_price_gbp,
				 flight_only_price_gbp__o,
				 flight_vat_on_commission_gbp,
				 flight_buy_rate_gbp,
				 flight_buy_rate_gbp__o,
				 total_received_from_user_gbp,
				 gross_revenue_sc,
				 customer_total_price_sc,
				 gross_booking_value_sc,
				 margin_gross_of_toms_sc,
				 margin_gross_of_toms_sc__o,
				 vat_on_commission_sc,
				 commission_ex_vat_sc,
				 booking_fee_sc,
				 booking_fee_net_rate_sc,
				 payment_surcharge_sc,
				 payment_surcharge_net_rate_sc,
				 insurance_commission_sc,
				 insurance_price_sc,
				 credits_used_sc,
				 cash_credits_used_sc,
				 non_cash_credits_used_sc,
				 total_custom_tax_sc,
				 atol_fee_sc,
				 total_sell_rate_sc,
				 flight_amount_sc,
				 flight_commission_sc,
				 flight_commission_sc__o,
				 flight_only_price_sc,
				 flight_only_price_sc__o,
				 flight_vat_on_commission_sc,
				 flight_buy_rate_sc,
				 flight_buy_rate_sc__o,
				 total_received_from_user_sc,
				 gross_revenue_eur_constant_currency,
				 margin_gross_of_toms_eur_constant_currency,
				 margin_current_eur_constant_currency,
				 mongo_total_price_sc,
				 mongo_commission_ex_vat_sc,
				 mongo_vat_on_commission_sc,
				 mongo_total_custom_tax_sc,
				 sale_id,
				 sale_name,
				 sale_base_currency,
				 sale_dimension,
				 offer_id,
				 offer_name,
				 offer_rate_code,
				 offer_travel_date_length,
				 board_basis,
				 room_name,
				 bundle_id,
				 check_in_date,
				 check_out_date,
				 booking_lead_time_days,
				 booking_type,
				 no_nights,
				 rooms,
				 room_nights,
				 adult_guests,
				 child_guests,
				 infant_guests,
				 top_discount,
				 sale_product,
				 sale_type,
				 booking_category,
				 has_flights,
				 inbound_flight_arrival_timestamp,
				 inbound_flight_arrival_date,
				 outbound_flight_departure_timestamp,
				 outbound_flight_departure_date,
				 departure_airport_code,
				 sale_closest_airport_code,
				 flight_carrier,
				 flight_invoice_number,
				 flight_supplier_name,
				 flight_supplier_reference,
				 flight_change_type_list,
				 flight_change_reason_list,
				 flight_adjustment_last_updated,
				 price_per_night,
				 price_per_person_per_night,
				 supplier_name,
				 provider_name,
				 rebooked,
				 date_of_rebooking,
				 original_check_in_date,
				 original_check_out_date,
				 voucher_stay_by_date,
				 is_new_model_booking,
				 is_staff_booking,
				 staff_booking_discount_type,
				 affiliate_id,
				 affiliate,
				 affiliate_domain,
				 agent_id,
				 payment_id,
				 hold_id,
				 insurance_provider,
				 payment_type,
				 zero_deposit_flag,
				 supplier_to_user_currency_exchange_rate_id,
				 is_affiliate_booking,
				 vcc_reference,
				 se_brand,
				 accommodation_channel_manager,
				 booking_present_in_chiasma,
				 refund_type,
				 total_refunded_cc,
				 total_refunded_gbp,
				 total_refunded_sc,
				 cancellation_date,
				 cancellation_tstamp,
				 cancellation_fault,
				 cancellation_reason,
				 cancellation_refund_channel,
				 cancellation_status,
				 cancellation_requested_by,
				 cancellation_requested_by_domain,
				 cancellation_payment_provider_refund_status,
				 cancellation_mode,
				 cancellation_policy_id,
				 is_cancellable,
				 cancellation_policy_number_of_days,
				 cancellation_policy_percentage) AS row_hash,

			booking_id,
			transaction_id,
			unique_transaction_reference,
			last_updated,
			last_updated_booking_summary,
			last_updated_bookings,
			last_updated_reservations,
			territory,
			booking_status,
			currency,
			booking_completed_date,
			booking_completed_timestamp,
			booking_created_date,
			booking_created_timestamp,
			cs_agent_booking,
			shiro_user_id,
			affiliate_user_id,
			device_platform,
			cc_rate_to_gbp,
			cc_rate_to_sc,
			gbp_rate_to_sc,
			reservation_exchange_rate_cc_to_sc,
			gross_revenue_cc,
			customer_total_price_cc,
			gross_booking_value_cc,
			margin_gross_of_toms_cc,
			margin_gross_of_toms_cc__o,
			margin_current_cc,
			vat_on_commission_cc,
			commission_ex_vat_cc,
			booking_fee_cc,
			booking_fee_net_rate_cc,
			payment_surcharge_cc,
			payment_surcharge_net_rate_cc,
			insurance_commission_cc,
			insurance_price_cc,
			credits_used_cc,
			cash_credits_used_cc,
			non_cash_credits_used_cc,
			total_custom_tax_cc,
			atol_fee_cc,
			total_sell_rate_cc,
			flight_amount_cc,
			flight_commission_cc,
			flight_commission_cc__o,
			flight_only_price_cc,
			flight_only_price_cc__o,
			flight_vat_on_commission_cc,
			flight_buy_rate_cc,
			flight_buy_rate_cc__o,
			total_received_from_user_cc,
			gross_revenue_gbp,
			gross_revenue_gbp_constant_currency,
			customer_total_price_gbp,
			customer_total_price_gbp_constant_currency,
			gross_booking_value_gbp,
			margin_gross_of_toms_gbp,
			margin_gross_of_toms_gbp__o,
			margin_gross_of_toms_gbp_constant_currency,
			margin_current_gbp,
			margin_current_gbp_constant_currency,
			vat_on_commission_gbp,
			commission_ex_vat_gbp,
			booking_fee_gbp,
			booking_fee_net_rate_gbp,
			payment_surcharge_gbp,
			payment_surcharge_net_rate_gbp,
			insurance_commission_gbp,
			insurance_price_gbp,
			credits_used_gbp,
			cash_credits_used_gbp,
			non_cash_credits_used_gbp,
			total_custom_tax_gbp,
			atol_fee_gbp,
			total_sell_rate_gbp,
			flight_amount_gbp,
			flight_commission_gbp,
			flight_commission_gbp__o,
			flight_only_price_gbp,
			flight_only_price_gbp__o,
			flight_vat_on_commission_gbp,
			flight_buy_rate_gbp,
			flight_buy_rate_gbp__o,
			total_received_from_user_gbp,
			gross_revenue_sc,
			customer_total_price_sc,
			gross_booking_value_sc,
			margin_gross_of_toms_sc,
			margin_gross_of_toms_sc__o,
			vat_on_commission_sc,
			commission_ex_vat_sc,
			booking_fee_sc,
			booking_fee_net_rate_sc,
			payment_surcharge_sc,
			payment_surcharge_net_rate_sc,
			insurance_commission_sc,
			insurance_price_sc,
			credits_used_sc,
			cash_credits_used_sc,
			non_cash_credits_used_sc,
			total_custom_tax_sc,
			atol_fee_sc,
			total_sell_rate_sc,
			flight_amount_sc,
			flight_commission_sc,
			flight_commission_sc__o,
			flight_only_price_sc,
			flight_only_price_sc__o,
			flight_vat_on_commission_sc,
			flight_buy_rate_sc,
			flight_buy_rate_sc__o,
			total_received_from_user_sc,
			gross_revenue_eur_constant_currency,
			margin_gross_of_toms_eur_constant_currency,
			margin_current_eur_constant_currency,
			mongo_total_price_sc,
			mongo_commission_ex_vat_sc,
			mongo_vat_on_commission_sc,
			mongo_total_custom_tax_sc,
			sale_id,
			sale_name,
			sale_base_currency,
			sale_dimension,
			offer_id,
			offer_name,
			offer_rate_code,
			offer_travel_date_length,
			board_basis,
			room_name,
			bundle_id,
			check_in_date,
			check_out_date,
			booking_lead_time_days,
			booking_type,
			no_nights,
			rooms,
			room_nights,
			adult_guests,
			child_guests,
			infant_guests,
			top_discount,
			sale_product,
			sale_type,
			booking_category,
			has_flights,
			inbound_flight_arrival_timestamp,
			inbound_flight_arrival_date,
			outbound_flight_departure_timestamp,
			outbound_flight_departure_date,
			departure_airport_code,
			sale_closest_airport_code,
			flight_carrier,
			flight_invoice_number,
			flight_supplier_name,
			flight_supplier_reference,
			flight_change_type_list,
			flight_change_reason_list,
			flight_adjustment_last_updated,
			price_per_night,
			price_per_person_per_night,
			supplier_name,
			provider_name,
			rebooked,
			date_of_rebooking,
			original_check_in_date,
			original_check_out_date,
			voucher_stay_by_date,
			is_new_model_booking,
			is_staff_booking,
			staff_booking_discount_type,
			affiliate_id,
			affiliate,
			affiliate_domain,
			agent_id,
			payment_id,
			hold_id,
			insurance_provider,
			payment_type,
			zero_deposit_flag,
			supplier_to_user_currency_exchange_rate_id,
			is_affiliate_booking,
			vcc_reference,
			se_brand,
			accommodation_channel_manager,
			booking_present_in_chiasma,
			refund_type,
			total_refunded_cc,
			total_refunded_gbp,
			total_refunded_sc,
			cancellation_date,
			cancellation_tstamp,
			cancellation_fault,
			cancellation_reason,
			cancellation_refund_channel,
			cancellation_status,
			cancellation_requested_by,
			cancellation_requested_by_domain,
			cancellation_payment_provider_refund_status,
			cancellation_mode,
			cancellation_policy_id,
			is_cancellable,
			cancellation_policy_number_of_days,
			cancellation_policy_percentage
		FROM data_vault_mvp.dwh.se_booking_snapshot AS se_booking_snapshot
		WHERE se_booking_snapshot.view_date >= CURRENT_DATE - 10
	)
SELECT *
FROM create_row_hash
QUALIFY
	ROW_NUMBER() OVER (PARTITION BY create_row_hash.booking_id, create_row_hash.row_hash ORDER BY create_row_hash.view_date ASC) =
	1
;

SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot -- 76,459,360
SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot_backup -- 840,826,220

SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
WHERE view_date >= CURRENT_DATE - 9 -- 20,629;


SELECT
	se_booking_snapshot.view_date,
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
WHERE view_date >= CURRENT_DATE - 9 -- 20,629;
GROUP BY ALL

SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot_backup
WHERE se_booking_snapshot_backup.view_date >= CURRENT_DATE - 9 -- 764,387,489;


SHOW TABLES IN SCHEMA data_vault_mvp_dev_robin.dwh
;

/*
bytes
se_booking_snapshot - 9,154,807,296
se_booking_snapshot_backup - 91,894,091,264
*/

/*
module=/biapp/task_catalogue/dv/dwh/transactional/se_booking_changelog.py make clones
*/



USE ROLE personal_role__robinpatel
;

CREATE SCHEMA IF NOT EXISTS data_vault_mvp_dev_robin.dwh
;

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking
	CLONE data_vault_mvp.dwh.se_booking
;

-- optional statement to create the module target table --
CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking_changelog
	CLONE data_vault_mvp.dwh.se_booking_changelog
;

self_describing_task
\
    --include 'biapp.task_catalogue.dv.dwh.transactional.se_booking_changelog.py' \
    --method 'run' \
    --start '2026-01-02 00:00:00' \
    --end '2026-01-02 00:00:00'


SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_changelog
;


SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_changelog
WHERE booking_id
		  IN (
			  '6846177', -- abandoned example
			  'A15118823', -- complete example
			  'A8017799' -- refunded example
		  )
;


TRUNCATE data_vault_mvp_dev_robin.dwh.se_booking_changelog
;

-- query to populate changelog from the existing snapshot table

USE WAREHOUSE pipe_4xlarge
;

INSERT INTO data_vault_mvp_dev_robin.dwh.se_booking_changelog
WITH
	create_row_hash AS (
		-- introduce a row_hash column to aid with merge and deletion
		SELECT
			schedule_tstamp,
			run_tstamp,
			operation_id,
			created_at,
			updated_at,
			view_date,
			HASH(booking_id,
				 transaction_id,
				 unique_transaction_reference,
				 last_updated,
				 last_updated_booking_summary,
				 last_updated_bookings,
				 last_updated_reservations,
				 territory,
				 booking_status,
				 currency,
				 booking_completed_date,
				 booking_completed_timestamp,
				 booking_created_date,
				 booking_created_timestamp,
				 cs_agent_booking,
				 shiro_user_id,
				 affiliate_user_id,
				 device_platform,
				 cc_rate_to_gbp,
				 cc_rate_to_sc,
				 gbp_rate_to_sc,
				 reservation_exchange_rate_cc_to_sc,
				 gross_revenue_cc,
				 customer_total_price_cc,
				 gross_booking_value_cc,
				 margin_gross_of_toms_cc,
				 margin_gross_of_toms_cc__o,
				 margin_current_cc,
				 vat_on_commission_cc,
				 commission_ex_vat_cc,
				 booking_fee_cc,
				 booking_fee_net_rate_cc,
				 payment_surcharge_cc,
				 payment_surcharge_net_rate_cc,
				 insurance_commission_cc,
				 insurance_price_cc,
				 credits_used_cc,
				 cash_credits_used_cc,
				 non_cash_credits_used_cc,
				 total_custom_tax_cc,
				 atol_fee_cc,
				 total_sell_rate_cc,
				 flight_amount_cc,
				 flight_commission_cc,
				 flight_commission_cc__o,
				 flight_only_price_cc,
				 flight_only_price_cc__o,
				 flight_vat_on_commission_cc,
				 flight_buy_rate_cc,
				 flight_buy_rate_cc__o,
				 total_received_from_user_cc,
				 gross_revenue_gbp,
				 gross_revenue_gbp_constant_currency,
				 customer_total_price_gbp,
				 customer_total_price_gbp_constant_currency,
				 gross_booking_value_gbp,
				 margin_gross_of_toms_gbp,
				 margin_gross_of_toms_gbp__o,
				 margin_gross_of_toms_gbp_constant_currency,
				 margin_current_gbp,
				 margin_current_gbp_constant_currency,
				 vat_on_commission_gbp,
				 commission_ex_vat_gbp,
				 booking_fee_gbp,
				 booking_fee_net_rate_gbp,
				 payment_surcharge_gbp,
				 payment_surcharge_net_rate_gbp,
				 insurance_commission_gbp,
				 insurance_price_gbp,
				 credits_used_gbp,
				 cash_credits_used_gbp,
				 non_cash_credits_used_gbp,
				 total_custom_tax_gbp,
				 atol_fee_gbp,
				 total_sell_rate_gbp,
				 flight_amount_gbp,
				 flight_commission_gbp,
				 flight_commission_gbp__o,
				 flight_only_price_gbp,
				 flight_only_price_gbp__o,
				 flight_vat_on_commission_gbp,
				 flight_buy_rate_gbp,
				 flight_buy_rate_gbp__o,
				 total_received_from_user_gbp,
				 gross_revenue_sc,
				 customer_total_price_sc,
				 gross_booking_value_sc,
				 margin_gross_of_toms_sc,
				 margin_gross_of_toms_sc__o,
				 vat_on_commission_sc,
				 commission_ex_vat_sc,
				 booking_fee_sc,
				 booking_fee_net_rate_sc,
				 payment_surcharge_sc,
				 payment_surcharge_net_rate_sc,
				 insurance_commission_sc,
				 insurance_price_sc,
				 credits_used_sc,
				 cash_credits_used_sc,
				 non_cash_credits_used_sc,
				 total_custom_tax_sc,
				 atol_fee_sc,
				 total_sell_rate_sc,
				 flight_amount_sc,
				 flight_commission_sc,
				 flight_commission_sc__o,
				 flight_only_price_sc,
				 flight_only_price_sc__o,
				 flight_vat_on_commission_sc,
				 flight_buy_rate_sc,
				 flight_buy_rate_sc__o,
				 total_received_from_user_sc,
				 gross_revenue_eur_constant_currency,
				 margin_gross_of_toms_eur_constant_currency,
				 margin_current_eur_constant_currency,
				 mongo_total_price_sc,
				 mongo_commission_ex_vat_sc,
				 mongo_vat_on_commission_sc,
				 mongo_total_custom_tax_sc,
				 sale_id,
				 sale_name,
				 sale_base_currency,
				 sale_dimension,
				 offer_id,
				 offer_name,
				 offer_rate_code,
				 offer_travel_date_length,
				 board_basis,
				 room_name,
				 bundle_id,
				 check_in_date,
				 check_out_date,
				 booking_lead_time_days,
				 booking_type,
				 no_nights,
				 rooms,
				 room_nights,
				 adult_guests,
				 child_guests,
				 infant_guests,
				 top_discount,
				 sale_product,
				 sale_type,
				 booking_category,
				 has_flights,
				 inbound_flight_arrival_timestamp,
				 inbound_flight_arrival_date,
				 outbound_flight_departure_timestamp,
				 outbound_flight_departure_date,
				 departure_airport_code,
				 sale_closest_airport_code,
				 flight_carrier,
				 flight_invoice_number,
				 flight_supplier_name,
				 flight_supplier_reference,
				 flight_change_type_list,
				 flight_change_reason_list,
				 flight_adjustment_last_updated,
				 price_per_night,
				 price_per_person_per_night,
				 supplier_name,
				 provider_name,
				 rebooked,
				 date_of_rebooking,
				 original_check_in_date,
				 original_check_out_date,
				 voucher_stay_by_date,
				 is_new_model_booking,
				 is_staff_booking,
				 staff_booking_discount_type,
				 affiliate_id,
				 affiliate,
				 affiliate_domain,
				 agent_id,
				 payment_id,
				 hold_id,
				 insurance_provider,
				 payment_type,
				 zero_deposit_flag,
				 supplier_to_user_currency_exchange_rate_id,
				 is_affiliate_booking,
				 vcc_reference,
				 se_brand,
				 accommodation_channel_manager,
				 booking_present_in_chiasma,
				 refund_type,
				 total_refunded_cc,
				 total_refunded_gbp,
				 total_refunded_sc,
				 cancellation_date,
				 cancellation_tstamp,
				 cancellation_fault,
				 cancellation_reason,
				 cancellation_refund_channel,
				 cancellation_status,
				 cancellation_requested_by,
				 cancellation_requested_by_domain,
				 cancellation_payment_provider_refund_status,
				 cancellation_mode,
				 cancellation_policy_id,
				 is_cancellable,
				 cancellation_policy_number_of_days,
				 cancellation_policy_percentage) AS row_hash,

			booking_id,
			transaction_id,
			unique_transaction_reference,
			last_updated,
			last_updated_booking_summary,
			last_updated_bookings,
			last_updated_reservations,
			territory,
			booking_status,
			currency,
			booking_completed_date,
			booking_completed_timestamp,
			booking_created_date,
			booking_created_timestamp,
			cs_agent_booking,
			shiro_user_id,
			affiliate_user_id,
			device_platform,
			cc_rate_to_gbp,
			cc_rate_to_sc,
			gbp_rate_to_sc,
			reservation_exchange_rate_cc_to_sc,
			gross_revenue_cc,
			customer_total_price_cc,
			gross_booking_value_cc,
			margin_gross_of_toms_cc,
			margin_gross_of_toms_cc__o,
			margin_current_cc,
			vat_on_commission_cc,
			commission_ex_vat_cc,
			booking_fee_cc,
			booking_fee_net_rate_cc,
			payment_surcharge_cc,
			payment_surcharge_net_rate_cc,
			insurance_commission_cc,
			insurance_price_cc,
			credits_used_cc,
			cash_credits_used_cc,
			non_cash_credits_used_cc,
			total_custom_tax_cc,
			atol_fee_cc,
			total_sell_rate_cc,
			flight_amount_cc,
			flight_commission_cc,
			flight_commission_cc__o,
			flight_only_price_cc,
			flight_only_price_cc__o,
			flight_vat_on_commission_cc,
			flight_buy_rate_cc,
			flight_buy_rate_cc__o,
			total_received_from_user_cc,
			gross_revenue_gbp,
			gross_revenue_gbp_constant_currency,
			customer_total_price_gbp,
			customer_total_price_gbp_constant_currency,
			gross_booking_value_gbp,
			margin_gross_of_toms_gbp,
			margin_gross_of_toms_gbp__o,
			margin_gross_of_toms_gbp_constant_currency,
			margin_current_gbp,
			margin_current_gbp_constant_currency,
			vat_on_commission_gbp,
			commission_ex_vat_gbp,
			booking_fee_gbp,
			booking_fee_net_rate_gbp,
			payment_surcharge_gbp,
			payment_surcharge_net_rate_gbp,
			insurance_commission_gbp,
			insurance_price_gbp,
			credits_used_gbp,
			cash_credits_used_gbp,
			non_cash_credits_used_gbp,
			total_custom_tax_gbp,
			atol_fee_gbp,
			total_sell_rate_gbp,
			flight_amount_gbp,
			flight_commission_gbp,
			flight_commission_gbp__o,
			flight_only_price_gbp,
			flight_only_price_gbp__o,
			flight_vat_on_commission_gbp,
			flight_buy_rate_gbp,
			flight_buy_rate_gbp__o,
			total_received_from_user_gbp,
			gross_revenue_sc,
			customer_total_price_sc,
			gross_booking_value_sc,
			margin_gross_of_toms_sc,
			margin_gross_of_toms_sc__o,
			vat_on_commission_sc,
			commission_ex_vat_sc,
			booking_fee_sc,
			booking_fee_net_rate_sc,
			payment_surcharge_sc,
			payment_surcharge_net_rate_sc,
			insurance_commission_sc,
			insurance_price_sc,
			credits_used_sc,
			cash_credits_used_sc,
			non_cash_credits_used_sc,
			total_custom_tax_sc,
			atol_fee_sc,
			total_sell_rate_sc,
			flight_amount_sc,
			flight_commission_sc,
			flight_commission_sc__o,
			flight_only_price_sc,
			flight_only_price_sc__o,
			flight_vat_on_commission_sc,
			flight_buy_rate_sc,
			flight_buy_rate_sc__o,
			total_received_from_user_sc,
			gross_revenue_eur_constant_currency,
			margin_gross_of_toms_eur_constant_currency,
			margin_current_eur_constant_currency,
			mongo_total_price_sc,
			mongo_commission_ex_vat_sc,
			mongo_vat_on_commission_sc,
			mongo_total_custom_tax_sc,
			sale_id,
			sale_name,
			sale_base_currency,
			sale_dimension,
			offer_id,
			offer_name,
			offer_rate_code,
			offer_travel_date_length,
			board_basis,
			room_name,
			bundle_id,
			check_in_date,
			check_out_date,
			booking_lead_time_days,
			booking_type,
			no_nights,
			rooms,
			room_nights,
			adult_guests,
			child_guests,
			infant_guests,
			top_discount,
			sale_product,
			sale_type,
			booking_category,
			has_flights,
			inbound_flight_arrival_timestamp,
			inbound_flight_arrival_date,
			outbound_flight_departure_timestamp,
			outbound_flight_departure_date,
			departure_airport_code,
			sale_closest_airport_code,
			flight_carrier,
			flight_invoice_number,
			flight_supplier_name,
			flight_supplier_reference,
			flight_change_type_list,
			flight_change_reason_list,
			flight_adjustment_last_updated,
			price_per_night,
			price_per_person_per_night,
			supplier_name,
			provider_name,
			rebooked,
			date_of_rebooking,
			original_check_in_date,
			original_check_out_date,
			voucher_stay_by_date,
			is_new_model_booking,
			is_staff_booking,
			staff_booking_discount_type,
			affiliate_id,
			affiliate,
			affiliate_domain,
			agent_id,
			payment_id,
			hold_id,
			insurance_provider,
			payment_type,
			zero_deposit_flag,
			supplier_to_user_currency_exchange_rate_id,
			is_affiliate_booking,
			vcc_reference,
			se_brand,
			accommodation_channel_manager,
			booking_present_in_chiasma,
			refund_type,
			total_refunded_cc,
			total_refunded_gbp,
			total_refunded_sc,
			cancellation_date,
			cancellation_tstamp,
			cancellation_fault,
			cancellation_reason,
			cancellation_refund_channel,
			cancellation_status,
			cancellation_requested_by,
			cancellation_requested_by_domain,
			cancellation_payment_provider_refund_status,
			cancellation_mode,
			cancellation_policy_id,
			is_cancellable,
			cancellation_policy_number_of_days,
			cancellation_policy_percentage
		FROM data_vault_mvp.dwh.se_booking_snapshot AS se_booking_snapshot
	)
SELECT *
FROM create_row_hash
QUALIFY
	ROW_NUMBER() OVER (PARTITION BY create_row_hash.booking_id, create_row_hash.row_hash ORDER BY create_row_hash.view_date ASC) =
	1
;

-- query id to run on entire table on a 4XL 01c176aa-0108-b018-0002-dd014383997b;


SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_changelog


CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking
	CLONE data_vault_mvp.dwh.se_booking
;

self_describing_task --include 'biapp/task_catalogue/dv/dwh/transactional/se_booking_changelog.py'  --method 'run' --start '2026-01-05 00:00:00' --end '2026-01-05 00:00:00'

;

USE ROLE pipelinerunner
;

CREATE OR REPLACE TABLE data_vault_mvp.dwh.se_booking_changelog CLONE data_vault_mvp_dev_robin.dwh.se_booking_changelog
;


USE ROLE personal_role__robinpatel
;


------------------------------------------------------------------------------------------------------------------------
-- se_booking_changelog deployed, now looking at creating se_booking_snapshot view so that we can remove persisted table


SELECT
	sbc.view_date,
	COUNT(*)
FROM data_vault_mvp.dwh.se_booking_changelog sbc
WHERE sbc.view_date >= CURRENT_DATE - 10
GROUP BY 1
;


SELECT *
FROM data_vault_mvp.dwh.se_booking_changelog sbc
WHERE sbc.view_date = CURRENT_DATE - 1
;

SELECT *
FROM data_vault_mvp.dwh.se_booking_changelog sbc
WHERE sbc.booking_id = '31035883'
;

SELECT *
FROM data_vault_mvp.dwh.se_booking_changelog sbc
WHERE sbc.booking_id = 'A22772553'
;


SELECT
	calendar.date_value            AS view_date,
	se_booking_changelog.view_date AS last_update_date,
	se_booking.booking_id,
	se_booking.transaction_id,
	se_booking.unique_transaction_reference,
	se_booking_changelog.row_hash,
	se_booking_changelog.last_updated,
	se_booking_changelog.last_updated_booking_summary,
	se_booking_changelog.last_updated_bookings,
	se_booking_changelog.last_updated_reservations,
	se_booking_changelog.territory,
	se_booking_changelog.booking_status,
	se_booking_changelog.currency,
	se_booking_changelog.booking_completed_date,
	se_booking_changelog.booking_completed_timestamp,
	se_booking_changelog.booking_created_date,
	se_booking_changelog.booking_created_timestamp,
	se_booking_changelog.cs_agent_booking,
	se_booking_changelog.shiro_user_id,
	se_booking_changelog.affiliate_user_id,
	se_booking_changelog.device_platform,
	se_booking_changelog.cc_rate_to_gbp,
	se_booking_changelog.cc_rate_to_sc,
	se_booking_changelog.gbp_rate_to_sc,
	se_booking_changelog.reservation_exchange_rate_cc_to_sc,
	se_booking_changelog.gross_revenue_cc,
	se_booking_changelog.customer_total_price_cc,
	se_booking_changelog.gross_booking_value_cc,
	se_booking_changelog.margin_gross_of_toms_cc,
	se_booking_changelog.margin_gross_of_toms_cc__o,
	se_booking_changelog.margin_current_cc,
	se_booking_changelog.vat_on_commission_cc,
	se_booking_changelog.commission_ex_vat_cc,
	se_booking_changelog.booking_fee_cc,
	se_booking_changelog.booking_fee_net_rate_cc,
	se_booking_changelog.payment_surcharge_cc,
	se_booking_changelog.payment_surcharge_net_rate_cc,
	se_booking_changelog.insurance_commission_cc,
	se_booking_changelog.insurance_price_cc,
	se_booking_changelog.credits_used_cc,
	se_booking_changelog.cash_credits_used_cc,
	se_booking_changelog.non_cash_credits_used_cc,
	se_booking_changelog.total_custom_tax_cc,
	se_booking_changelog.atol_fee_cc,
	se_booking_changelog.total_sell_rate_cc,
	se_booking_changelog.flight_amount_cc,
	se_booking_changelog.flight_commission_cc,
	se_booking_changelog.flight_commission_cc__o,
	se_booking_changelog.flight_only_price_cc,
	se_booking_changelog.flight_only_price_cc__o,
	se_booking_changelog.flight_vat_on_commission_cc,
	se_booking_changelog.flight_buy_rate_cc,
	se_booking_changelog.flight_buy_rate_cc__o,
	se_booking_changelog.total_received_from_user_cc,
	se_booking_changelog.gross_revenue_gbp,
	se_booking_changelog.gross_revenue_gbp_constant_currency,
	se_booking_changelog.customer_total_price_gbp,
	se_booking_changelog.customer_total_price_gbp_constant_currency,
	se_booking_changelog.gross_booking_value_gbp,
	se_booking_changelog.margin_gross_of_toms_gbp,
	se_booking_changelog.margin_gross_of_toms_gbp__o,
	se_booking_changelog.margin_gross_of_toms_gbp_constant_currency,
	se_booking_changelog.margin_current_gbp,
	se_booking_changelog.margin_current_gbp_constant_currency,
	se_booking_changelog.vat_on_commission_gbp,
	se_booking_changelog.commission_ex_vat_gbp,
	se_booking_changelog.booking_fee_gbp,
	se_booking_changelog.booking_fee_net_rate_gbp,
	se_booking_changelog.payment_surcharge_gbp,
	se_booking_changelog.payment_surcharge_net_rate_gbp,
	se_booking_changelog.insurance_commission_gbp,
	se_booking_changelog.insurance_price_gbp,
	se_booking_changelog.credits_used_gbp,
	se_booking_changelog.cash_credits_used_gbp,
	se_booking_changelog.non_cash_credits_used_gbp,
	se_booking_changelog.total_custom_tax_gbp,
	se_booking_changelog.atol_fee_gbp,
	se_booking_changelog.total_sell_rate_gbp,
	se_booking_changelog.flight_amount_gbp,
	se_booking_changelog.flight_commission_gbp,
	se_booking_changelog.flight_commission_gbp__o,
	se_booking_changelog.flight_only_price_gbp,
	se_booking_changelog.flight_only_price_gbp__o,
	se_booking_changelog.flight_vat_on_commission_gbp,
	se_booking_changelog.flight_buy_rate_gbp,
	se_booking_changelog.flight_buy_rate_gbp__o,
	se_booking_changelog.total_received_from_user_gbp,
	se_booking_changelog.gross_revenue_sc,
	se_booking_changelog.customer_total_price_sc,
	se_booking_changelog.gross_booking_value_sc,
	se_booking_changelog.margin_gross_of_toms_sc,
	se_booking_changelog.margin_gross_of_toms_sc__o,
	se_booking_changelog.vat_on_commission_sc,
	se_booking_changelog.commission_ex_vat_sc,
	se_booking_changelog.booking_fee_sc,
	se_booking_changelog.booking_fee_net_rate_sc,
	se_booking_changelog.payment_surcharge_sc,
	se_booking_changelog.payment_surcharge_net_rate_sc,
	se_booking_changelog.insurance_commission_sc,
	se_booking_changelog.insurance_price_sc,
	se_booking_changelog.credits_used_sc,
	se_booking_changelog.cash_credits_used_sc,
	se_booking_changelog.non_cash_credits_used_sc,
	se_booking_changelog.total_custom_tax_sc,
	se_booking_changelog.atol_fee_sc,
	se_booking_changelog.total_sell_rate_sc,
	se_booking_changelog.flight_amount_sc,
	se_booking_changelog.flight_commission_sc,
	se_booking_changelog.flight_commission_sc__o,
	se_booking_changelog.flight_only_price_sc,
	se_booking_changelog.flight_only_price_sc__o,
	se_booking_changelog.flight_vat_on_commission_sc,
	se_booking_changelog.flight_buy_rate_sc,
	se_booking_changelog.flight_buy_rate_sc__o,
	se_booking_changelog.total_received_from_user_sc,
	se_booking_changelog.gross_revenue_eur_constant_currency,
	se_booking_changelog.margin_gross_of_toms_eur_constant_currency,
	se_booking_changelog.margin_current_eur_constant_currency,
	se_booking_changelog.mongo_total_price_sc,
	se_booking_changelog.mongo_commission_ex_vat_sc,
	se_booking_changelog.mongo_vat_on_commission_sc,
	se_booking_changelog.mongo_total_custom_tax_sc,
	se_booking_changelog.sale_id,
	se_booking_changelog.sale_name,
	se_booking_changelog.sale_base_currency,
	se_booking_changelog.sale_dimension,
	se_booking_changelog.offer_id,
	se_booking_changelog.offer_name,
	se_booking_changelog.offer_rate_code,
	se_booking_changelog.offer_travel_date_length,
	se_booking_changelog.board_basis,
	se_booking_changelog.room_name,
	se_booking_changelog.bundle_id,
	se_booking_changelog.check_in_date,
	se_booking_changelog.check_out_date,
	se_booking_changelog.booking_lead_time_days,
	se_booking_changelog.booking_type,
	se_booking_changelog.no_nights,
	se_booking_changelog.rooms,
	se_booking_changelog.room_nights,
	se_booking_changelog.adult_guests,
	se_booking_changelog.child_guests,
	se_booking_changelog.infant_guests,
	se_booking_changelog.top_discount,
	se_booking_changelog.sale_product,
	se_booking_changelog.sale_type,
	se_booking_changelog.booking_category,
	se_booking_changelog.has_flights,
	se_booking_changelog.inbound_flight_arrival_timestamp,
	se_booking_changelog.inbound_flight_arrival_date,
	se_booking_changelog.outbound_flight_departure_timestamp,
	se_booking_changelog.outbound_flight_departure_date,
	se_booking_changelog.departure_airport_code,
	se_booking_changelog.sale_closest_airport_code,
	se_booking_changelog.flight_carrier,
	se_booking_changelog.flight_invoice_number,
	se_booking_changelog.flight_supplier_name,
	se_booking_changelog.flight_supplier_reference,
	se_booking_changelog.flight_change_type_list,
	se_booking_changelog.flight_change_reason_list,
	se_booking_changelog.flight_adjustment_last_updated,
	se_booking_changelog.price_per_night,
	se_booking_changelog.price_per_person_per_night,
	se_booking_changelog.supplier_name,
	se_booking_changelog.provider_name,
	se_booking_changelog.rebooked,
	se_booking_changelog.date_of_rebooking,
	se_booking_changelog.original_check_in_date,
	se_booking_changelog.original_check_out_date,
	se_booking_changelog.voucher_stay_by_date,
	se_booking_changelog.is_new_model_booking,
	se_booking_changelog.is_staff_booking,
	se_booking_changelog.staff_booking_discount_type,
	se_booking_changelog.affiliate_id,
	se_booking_changelog.affiliate,
	se_booking_changelog.affiliate_domain,
	se_booking_changelog.agent_id,
	se_booking_changelog.payment_id,
	se_booking_changelog.hold_id,
	se_booking_changelog.insurance_provider,
	se_booking_changelog.payment_type,
	se_booking_changelog.zero_deposit_flag,
	se_booking_changelog.supplier_to_user_currency_exchange_rate_id,
	se_booking_changelog.is_affiliate_booking,
	se_booking_changelog.vcc_reference,
	se_booking_changelog.se_brand,
	se_booking_changelog.accommodation_channel_manager,
	se_booking_changelog.booking_present_in_chiasma,
	se_booking_changelog.refund_type,
	se_booking_changelog.total_refunded_cc,
	se_booking_changelog.total_refunded_gbp,
	se_booking_changelog.total_refunded_sc,
	se_booking_changelog.cancellation_date,
	se_booking_changelog.cancellation_tstamp,
	se_booking_changelog.cancellation_fault,
	se_booking_changelog.cancellation_reason,
	se_booking_changelog.cancellation_refund_channel,
	se_booking_changelog.cancellation_status,
	se_booking_changelog.cancellation_requested_by,
	se_booking_changelog.cancellation_requested_by_domain,
	se_booking_changelog.cancellation_payment_provider_refund_status,
	se_booking_changelog.cancellation_mode,
	se_booking_changelog.cancellation_policy_id,
	se_booking_changelog.is_cancellable,
	se_booking_changelog.cancellation_policy_number_of_days,
	se_booking_changelog.cancellation_policy_percentage
FROM se.data.se_booking se_booking
-- explode out booking by day, don't include day of booking as this would not have yet been considered in the snapshot/changelog process
INNER JOIN data_vault_mvp.dwh.se_calendar calendar
	ON se_booking.booking_created_date < calendar.date_value
	AND calendar.date_value <= CURRENT_DATE
ASOF JOIN data_vault_mvp.dwh.se_booking_changelog se_booking_changelog
MATCH_CONDITION (calendar.date_value >= se_booking_changelog.view_date)
	ON se_booking.booking_id = se_booking_changelog.booking_id
WHERE se_booking.booking_id = 'A22772553' -- TODO REMOVE;

USE WAREHOUSE pipe_xlarge
;

SELECT *
FROM data_vault_mvp.dwh.se_booking_snapshot sbs
WHERE sbs.booking_id = 'A22772553'
;



module=/
biapp/
task_catalogue/
dv/
dwh/
transactional/
se_booking_snapshot.py make clones

CREATE OR REPLACE VIEW data_vault_mvp_dev_robin.dwh.se_calendar AS
SELECT *
FROM data_vault_mvp.dwh.se_calendar
;

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking CLONE data_vault_mvp.dwh.se_booking
;

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.se_booking_changelog CLONE data_vault_mvp.dwh.se_booking_changelog
;

SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
WHERE booking_id = 'A22772553'
;


SELECT *
FROM data_vault_mvp.dwh.se_booking_snapshot
WHERE booking_id = 'A22772553'
;


SELECT
	COUNT(*)
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
;


SELECT
	COUNT(*)
FROM data_vault_mvp.dwh.se_booking_snapshot
;


SELECT
	COUNT(*)
FROM data_vault_mvp.dwh.se_booking_changelog sbc --  324,366,543
SELECT
	COUNT(*)
FROM data_vault_mvp.dwh.se_booking_snapshot sbs -- 79,474,552,608


SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
LIMIT 500
;

SELECT *
FROM data_vault_mvp_dev_robin.dwh.se_booking_snapshot
WHERE se_booking_snapshot.view_date >= CURRENT_DATE - 10;