dataset_task --include 'se_api.sales_kingfisher' --operation ExtractOperation --method 'run'  --start '2023-07-24 00:30:00' --end '2023-07-25 00:30:00'
dataset_task --include 'se_api.sales_kingfisher' --operation IngestOperation --method 'run'  --start '2023-07-24 00:30:00' --end '2023-07-25 00:30:00'
dataset_task --include 'se_api.sales_kingfisher' --operation HygieneOperation --method 'run'  --start '2023-07-24 00:30:00' --end '2023-07-25 00:30:00'
dataset_task --include 'se_api.sales_kingfisher' --operation LatestRecordsOperation --method 'run' --upstream --start '2023-07-25 00:00:00' --end '2023-07-25 00:00:00'

CREATE SCHEMA raw_vault_dev_robin.se_api
;

CREATE SCHEMA hygiene_vault_dev_robin.se_api
;

CREATE SCHEMA latest_vault_dev_robin.se_api
;

CREATE OR REPLACE TRANSIENT TABLE latest_vault_dev_robin.cms_mysql.affiliate CLONE latest_vault.cms_mysql.affiliate
;

CREATE OR REPLACE TRANSIENT TABLE latest_vault_dev_robin.cms_mysql.base_offer_translation CLONE latest_vault.cms_mysql.base_offer_translation
;

CREATE OR REPLACE TRANSIENT TABLE latest_vault_dev_robin.cms_mysql.hotel_sale_offer CLONE latest_vault.cms_mysql.hotel_sale_offer
;
-- CREATE OR REPLACE TRANSIENT TABLE latest_vault_dev_robin.se_api.sales_kingfisher CLONE latest_vault.se_api.sales_kingfisher;
CREATE OR REPLACE TRANSIENT TABLE latest_vault_dev_robin.cms_mysql.territory CLONE latest_vault.cms_mysql.territory
;

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp_dev_robin.dwh.user_booking_review CLONE data_vault_mvp.dwh.user_booking_review
;

self_describing_task --include 'biapp/task_catalogue/dv/dwh/iterable/catalogue_product.py'  --method 'run' --start '2023-07-25 00:00:00' --end '2023-07-25 00:00:00'
self_describing_task --include 'biapp/task_catalogue/staging/outgoing/iterable/catalogue_product_sandbox/modelling.py'  --method 'run' --start '2023-07-25 08:00:00' --end '2023-07-25 08:00:00'
dataset_task --include 'outgoing.iterable.catalogue_product_sandbox' --operation UnloadOperation --method 'run' --start '2023-07-25 08:00:00' --end '2023-07-25 08:00:00'
dataset_task --include 'outgoing.iterable.catalogue_product_sandbox' --operation DistributeOperation --method 'run' --start '2023-07-25 08:00:00' --end '2023-07-25 08:00:00'



------------------------------------------------------------------------------------------------------------------------
--backup table

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp.dwh.iterable__catalogue_product_20230726 CLONE data_vault_mvp.dwh.iterable__catalogue_product
;

BEGIN TRANSACTION
;

-- create temp table with new structure
CREATE TABLE IF NOT EXISTS data_vault_mvp.dwh.iterable__catalogue_product__temp
(
	-- (lineage) metadata for the current job
	schedule_tstamp                          TIMESTAMP,
	run_tstamp                               TIMESTAMP,
	operation_id                             VARCHAR,
	created_at                               TIMESTAMP,
	updated_at                               TIMESTAMP,

	compound_id                              VARCHAR PRIMARY KEY NOT NULL,
	se_sale_id                               VARCHAR,
	id                                       VARCHAR,
	affiliate_active                         BOOLEAN,
	affiliate_domain                         VARCHAR,
	affiliate_id                             NUMBER,
	affiliate_is_default                     BOOLEAN,
	affiliate_is_main_for_domain             BOOLEAN,
	affiliate_name                           VARCHAR,
	affiliate_sale_url                       VARCHAR,
	affiliate_url_string                     VARCHAR,
	badges                                   ARRAY,
	cancellation_description                 VARCHAR,
	cancellation_description_warning         VARCHAR,
	cancellation_summary                     VARCHAR,
	city_district_id                         VARCHAR,
	city_district_name                       VARCHAR,
	city_id                                  NUMBER,
	city_name                                VARCHAR,
	continent_id                             NUMBER,
	continent_name                           VARCHAR,
	country_id                               NUMBER,
	country_name                             VARCHAR,
	currency_code                            VARCHAR,
	current_sale                             BOOLEAN,
	current_sale_visitors                    NUMBER,
	dates_end                                TIMESTAMP_NTZ,
	dates_start                              TIMESTAMP_NTZ,
	deal_includes                            VARCHAR,
	deposit_from_price_for_display           VARCHAR,
	deposit_from_price_unit                  DECIMAL(13, 2),
	deposit_from_price_unit_per_person       DECIMAL(13, 2),
	destination_name                         VARCHAR,
	discount                                 DECIMAL(13, 2),
	discount_display                         VARCHAR,
	discount_tooltip                         VARCHAR,
	display_order                            NUMBER,
	division_id                              NUMBER,
	division_name                            VARCHAR,
	end_date_display                         VARCHAR,
	has_flights_available                    BOOLEAN,
	has_flights_included                     BOOLEAN,
	hash                                     VARCHAR,
	hotel_details                            VARCHAR,
	is_catalogue                             BOOLEAN,
	is_connected                             BOOLEAN,
	is_current                               BOOLEAN,
	is_deposit_sale                          BOOLEAN,
	is_dynamic_package                       BOOLEAN,
	is_editors_pick                          BOOLEAN,
	is_exclusive                             BOOLEAN,
	is_hidden_for_app                        BOOLEAN,
	is_hidden_for_whitelabels                BOOLEAN,
	is_hotel_chain                           BOOLEAN,
	is_mysterious                            BOOLEAN,
	is_package                               BOOLEAN,
	is_refundable                            BOOLEAN,
	is_smart_stay                            BOOLEAN,
	is_time_limited                          BOOLEAN,
	is_zero_deposit                          BOOLEAN,
	latitude                                 DECIMAL(9, 6),
	lead_image_url_array                     ARRAY,
	lead_image_url_with_size_array           ARRAY,
	lead_rate_for_display                    VARCHAR,
	lead_rate_label                          VARCHAR,
	lead_rate_tooltip                        VARCHAR,
	lead_rate_unit                           DECIMAL(13, 2),
	lead_rate_unit_label                     VARCHAR,
	lead_rate_unit_per_person                DECIMAL(13, 2),
	links_price_comparison                   VARCHAR,
	links_sale                               VARCHAR,
	links_trip_advisor                       VARCHAR,
	longitude                                DECIMAL(9, 6),
	main_paragraph                           VARCHAR,
	max_number_of_adults                     NUMBER,
	month_availability                       ARRAY,
	number_of_hotel_nights                   NUMBER,
	offer_ids                                ARRAY,
	photos                                   ARRAY,
	pricing_model_for_display                VARCHAR,
	promotion                                VARCHAR,
	rack_rate_for_display                    VARCHAR,
	rack_rate_unit                           DECIMAL(13, 2),
	rack_rate_unit_per_person                DECIMAL(13, 2),
	reason_to_love                           VARCHAR,
	record                                   VARIANT,
	room_description                         VARCHAR,
	row_hash                                 VARCHAR,
	sale_active                              BOOLEAN,
	sale_url                                 VARCHAR,
	second_opinion                           VARCHAR,
	total_price_for_display                  VARCHAR,
	show_discount                            BOOLEAN,
	show_prices                              BOOLEAN,
	show_rack_rate                           BOOLEAN,
	summary                                  VARCHAR,
	tags                                     ARRAY,
	territory                                VARCHAR,
	territory_id                             NUMBER,
	territory_locale                         VARCHAR,
	times_booked                             NUMBER,
	title                                    VARCHAR,
	travel_details                           VARCHAR,
	travel_type                              VARCHAR,
	type                                     VARCHAR,
	we_like                                  VARCHAR,
	no_of_reviews                            INTEGER,
	average_review_score_zero_to_five        DECIMAL(13, 2),
	average_review_score_zero_to_ten         DECIMAL(13, 2),
	offer_inclusions_english_locale          ARRAY,
	offer_inclusions_territory_locale        ARRAY,
	common_offer_inclusions_english_locale   ARRAY,
	common_offer_inclusions_territory_locale ARRAY
)
;

-- insert data with nulls in total_price_for_display for history
INSERT INTO data_vault_mvp.dwh.iterable__catalogue_product__temp
SELECT
	iterable__catalogue_product.schedule_tstamp,
	iterable__catalogue_product.run_tstamp,
	iterable__catalogue_product.operation_id,
	iterable__catalogue_product.created_at,
	iterable__catalogue_product.updated_at,
	iterable__catalogue_product.compound_id,
	iterable__catalogue_product.se_sale_id,
	iterable__catalogue_product.id,
	iterable__catalogue_product.affiliate_active,
	iterable__catalogue_product.affiliate_domain,
	iterable__catalogue_product.affiliate_id,
	iterable__catalogue_product.affiliate_is_default,
	iterable__catalogue_product.affiliate_is_main_for_domain,
	iterable__catalogue_product.affiliate_name,
	iterable__catalogue_product.affiliate_sale_url,
	iterable__catalogue_product.affiliate_url_string,
	iterable__catalogue_product.badges,
	iterable__catalogue_product.cancellation_description,
	iterable__catalogue_product.cancellation_description_warning,
	iterable__catalogue_product.cancellation_summary,
	iterable__catalogue_product.city_district_id,
	iterable__catalogue_product.city_district_name,
	iterable__catalogue_product.city_id,
	iterable__catalogue_product.city_name,
	iterable__catalogue_product.continent_id,
	iterable__catalogue_product.continent_name,
	iterable__catalogue_product.country_id,
	iterable__catalogue_product.country_name,
	iterable__catalogue_product.currency_code,
	iterable__catalogue_product.current_sale,
	iterable__catalogue_product.current_sale_visitors,
	iterable__catalogue_product.dates_end,
	iterable__catalogue_product.dates_start,
	iterable__catalogue_product.deal_includes,
	iterable__catalogue_product.deposit_from_price_for_display,
	iterable__catalogue_product.deposit_from_price_unit,
	iterable__catalogue_product.deposit_from_price_unit_per_person,
	iterable__catalogue_product.destination_name,
	iterable__catalogue_product.discount,
	iterable__catalogue_product.discount_display,
	iterable__catalogue_product.discount_tooltip,
	iterable__catalogue_product.display_order,
	iterable__catalogue_product.division_id,
	iterable__catalogue_product.division_name,
	iterable__catalogue_product.end_date_display,
	iterable__catalogue_product.has_flights_available,
	iterable__catalogue_product.has_flights_included,
	iterable__catalogue_product.hash,
	iterable__catalogue_product.hotel_details,
	iterable__catalogue_product.is_catalogue,
	iterable__catalogue_product.is_connected,
	iterable__catalogue_product.is_current,
	iterable__catalogue_product.is_deposit_sale,
	iterable__catalogue_product.is_dynamic_package,
	iterable__catalogue_product.is_editors_pick,
	iterable__catalogue_product.is_exclusive,
	iterable__catalogue_product.is_hidden_for_app,
	iterable__catalogue_product.is_hidden_for_whitelabels,
	iterable__catalogue_product.is_hotel_chain,
	iterable__catalogue_product.is_mysterious,
	iterable__catalogue_product.is_package,
	iterable__catalogue_product.is_refundable,
	iterable__catalogue_product.is_smart_stay,
	iterable__catalogue_product.is_time_limited,
	iterable__catalogue_product.is_zero_deposit,
	iterable__catalogue_product.latitude,
	iterable__catalogue_product.lead_image_url_array,
	iterable__catalogue_product.lead_image_url_with_size_array,
	iterable__catalogue_product.lead_rate_for_display,
	iterable__catalogue_product.lead_rate_label,
	iterable__catalogue_product.lead_rate_tooltip,
	iterable__catalogue_product.lead_rate_unit,
	iterable__catalogue_product.lead_rate_unit_label,
	iterable__catalogue_product.lead_rate_unit_per_person,
	iterable__catalogue_product.links_price_comparison,
	iterable__catalogue_product.links_sale,
	iterable__catalogue_product.links_trip_advisor,
	iterable__catalogue_product.longitude,
	iterable__catalogue_product.main_paragraph,
	iterable__catalogue_product.max_number_of_adults,
	iterable__catalogue_product.month_availability,
	iterable__catalogue_product.number_of_hotel_nights,
	iterable__catalogue_product.offer_ids,
	iterable__catalogue_product.photos,
	iterable__catalogue_product.pricing_model_for_display,
	iterable__catalogue_product.promotion,
	iterable__catalogue_product.rack_rate_for_display,
	iterable__catalogue_product.rack_rate_unit,
	iterable__catalogue_product.rack_rate_unit_per_person,
	iterable__catalogue_product.reason_to_love,
	iterable__catalogue_product.record,
	iterable__catalogue_product.room_description,
	iterable__catalogue_product.row_hash,
	iterable__catalogue_product.sale_active,
	iterable__catalogue_product.sale_url,
	iterable__catalogue_product.second_opinion,
	NULL AS total_price_for_display,
	iterable__catalogue_product.show_discount,
	iterable__catalogue_product.show_prices,
	iterable__catalogue_product.show_rack_rate,
	iterable__catalogue_product.summary,
	iterable__catalogue_product.tags,
	iterable__catalogue_product.territory,
	iterable__catalogue_product.territory_id,
	iterable__catalogue_product.territory_locale,
	iterable__catalogue_product.times_booked,
	iterable__catalogue_product.title,
	iterable__catalogue_product.travel_details,
	iterable__catalogue_product.travel_type,
	iterable__catalogue_product.type,
	iterable__catalogue_product.we_like,
	iterable__catalogue_product.no_of_reviews,
	iterable__catalogue_product.average_review_score_zero_to_five,
	iterable__catalogue_product.average_review_score_zero_to_ten,
	iterable__catalogue_product.offer_inclusions_english_locale,
	iterable__catalogue_product.offer_inclusions_territory_locale,
	iterable__catalogue_product.common_offer_inclusions_english_locale,
	iterable__catalogue_product.common_offer_inclusions_territory_locale
FROM data_vault_mvp.dwh.iterable__catalogue_product
;

--swap table back in
CREATE OR REPLACE TABLE data_vault_mvp_dev_robin.dwh.iterable__catalogue_product CLONE data_vault_mvp_dev_robin.dwh.iterable__catalogue_product__temp
;

COMMIT
;
-- drop clone
DROP TABLE data_vault_mvp.dwh.iterable__catalogue_product__temp;

-- Rerun dag for current run -- dwh__iterable__catalogue_product__hourly



------------------------------------------------------------------------------------------------------------------------
USE role pipelinerunner;

--backup table

CREATE OR REPLACE TRANSIENT TABLE data_vault_mvp.dwh.iterable__catalogue_product_20230726 CLONE data_vault_mvp.dwh.iterable__catalogue_product
;

BEGIN TRANSACTION
;

-- create temp table with new structure
CREATE TABLE IF NOT EXISTS data_vault_mvp.dwh.iterable__catalogue_product__temp
(
	-- (lineage) metadata for the current job
	schedule_tstamp                          TIMESTAMP,
	run_tstamp                               TIMESTAMP,
	operation_id                             VARCHAR,
	created_at                               TIMESTAMP,
	updated_at                               TIMESTAMP,

	compound_id                              VARCHAR PRIMARY KEY NOT NULL,
	se_sale_id                               VARCHAR,
	id                                       VARCHAR,
	affiliate_active                         BOOLEAN,
	affiliate_domain                         VARCHAR,
	affiliate_id                             NUMBER,
	affiliate_is_default                     BOOLEAN,
	affiliate_is_main_for_domain             BOOLEAN,
	affiliate_name                           VARCHAR,
	affiliate_sale_url                       VARCHAR,
	affiliate_url_string                     VARCHAR,
	badges                                   ARRAY,
	cancellation_description                 VARCHAR,
	cancellation_description_warning         VARCHAR,
	cancellation_summary                     VARCHAR,
	city_district_id                         VARCHAR,
	city_district_name                       VARCHAR,
	city_id                                  NUMBER,
	city_name                                VARCHAR,
	continent_id                             NUMBER,
	continent_name                           VARCHAR,
	country_id                               NUMBER,
	country_name                             VARCHAR,
	currency_code                            VARCHAR,
	current_sale                             BOOLEAN,
	current_sale_visitors                    NUMBER,
	dates_end                                TIMESTAMP_NTZ,
	dates_start                              TIMESTAMP_NTZ,
	deal_includes                            VARCHAR,
	deposit_from_price_for_display           VARCHAR,
	deposit_from_price_unit                  DECIMAL(13, 2),
	deposit_from_price_unit_per_person       DECIMAL(13, 2),
	destination_name                         VARCHAR,
	discount                                 DECIMAL(13, 2),
	discount_display                         VARCHAR,
	discount_tooltip                         VARCHAR,
	display_order                            NUMBER,
	division_id                              NUMBER,
	division_name                            VARCHAR,
	end_date_display                         VARCHAR,
	has_flights_available                    BOOLEAN,
	has_flights_included                     BOOLEAN,
	hash                                     VARCHAR,
	hotel_details                            VARCHAR,
	is_catalogue                             BOOLEAN,
	is_connected                             BOOLEAN,
	is_current                               BOOLEAN,
	is_deposit_sale                          BOOLEAN,
	is_dynamic_package                       BOOLEAN,
	is_editors_pick                          BOOLEAN,
	is_exclusive                             BOOLEAN,
	is_hidden_for_app                        BOOLEAN,
	is_hidden_for_whitelabels                BOOLEAN,
	is_hotel_chain                           BOOLEAN,
	is_mysterious                            BOOLEAN,
	is_package                               BOOLEAN,
	is_refundable                            BOOLEAN,
	is_smart_stay                            BOOLEAN,
	is_time_limited                          BOOLEAN,
	is_zero_deposit                          BOOLEAN,
	latitude                                 DECIMAL(9, 6),
	lead_image_url_array                     ARRAY,
	lead_image_url_with_size_array           ARRAY,
	lead_rate_for_display                    VARCHAR,
	lead_rate_label                          VARCHAR,
	lead_rate_tooltip                        VARCHAR,
	lead_rate_unit                           DECIMAL(13, 2),
	lead_rate_unit_label                     VARCHAR,
	lead_rate_unit_per_person                DECIMAL(13, 2),
	links_price_comparison                   VARCHAR,
	links_sale                               VARCHAR,
	links_trip_advisor                       VARCHAR,
	longitude                                DECIMAL(9, 6),
	main_paragraph                           VARCHAR,
	max_number_of_adults                     NUMBER,
	month_availability                       ARRAY,
	number_of_hotel_nights                   NUMBER,
	offer_ids                                ARRAY,
	photos                                   ARRAY,
	pricing_model_for_display                VARCHAR,
	promotion                                VARCHAR,
	rack_rate_for_display                    VARCHAR,
	rack_rate_unit                           DECIMAL(13, 2),
	rack_rate_unit_per_person                DECIMAL(13, 2),
	reason_to_love                           VARCHAR,
	record                                   VARIANT,
	room_description                         VARCHAR,
	row_hash                                 VARCHAR,
	sale_active                              BOOLEAN,
	sale_url                                 VARCHAR,
	second_opinion                           VARCHAR,
	total_price_for_display                  VARCHAR,
	show_discount                            BOOLEAN,
	show_prices                              BOOLEAN,
	show_rack_rate                           BOOLEAN,
	summary                                  VARCHAR,
	tags                                     ARRAY,
	territory                                VARCHAR,
	territory_id                             NUMBER,
	territory_locale                         VARCHAR,
	times_booked                             NUMBER,
	title                                    VARCHAR,
	travel_details                           VARCHAR,
	travel_type                              VARCHAR,
	type                                     VARCHAR,
	we_like                                  VARCHAR,
	no_of_reviews                            INTEGER,
	average_review_score_zero_to_five        DECIMAL(13, 2),
	average_review_score_zero_to_ten         DECIMAL(13, 2),
	offer_inclusions_english_locale          ARRAY,
	offer_inclusions_territory_locale        ARRAY,
	common_offer_inclusions_english_locale   ARRAY,
	common_offer_inclusions_territory_locale ARRAY
)
;

-- insert data with nulls in total_price_for_display for history
INSERT INTO data_vault_mvp.dwh.iterable__catalogue_product__temp
SELECT
	iterable__catalogue_product.schedule_tstamp,
	iterable__catalogue_product.run_tstamp,
	iterable__catalogue_product.operation_id,
	iterable__catalogue_product.created_at,
	iterable__catalogue_product.updated_at,
	iterable__catalogue_product.compound_id,
	iterable__catalogue_product.se_sale_id,
	iterable__catalogue_product.id,
	iterable__catalogue_product.affiliate_active,
	iterable__catalogue_product.affiliate_domain,
	iterable__catalogue_product.affiliate_id,
	iterable__catalogue_product.affiliate_is_default,
	iterable__catalogue_product.affiliate_is_main_for_domain,
	iterable__catalogue_product.affiliate_name,
	iterable__catalogue_product.affiliate_sale_url,
	iterable__catalogue_product.affiliate_url_string,
	iterable__catalogue_product.badges,
	iterable__catalogue_product.cancellation_description,
	iterable__catalogue_product.cancellation_description_warning,
	iterable__catalogue_product.cancellation_summary,
	iterable__catalogue_product.city_district_id,
	iterable__catalogue_product.city_district_name,
	iterable__catalogue_product.city_id,
	iterable__catalogue_product.city_name,
	iterable__catalogue_product.continent_id,
	iterable__catalogue_product.continent_name,
	iterable__catalogue_product.country_id,
	iterable__catalogue_product.country_name,
	iterable__catalogue_product.currency_code,
	iterable__catalogue_product.current_sale,
	iterable__catalogue_product.current_sale_visitors,
	iterable__catalogue_product.dates_end,
	iterable__catalogue_product.dates_start,
	iterable__catalogue_product.deal_includes,
	iterable__catalogue_product.deposit_from_price_for_display,
	iterable__catalogue_product.deposit_from_price_unit,
	iterable__catalogue_product.deposit_from_price_unit_per_person,
	iterable__catalogue_product.destination_name,
	iterable__catalogue_product.discount,
	iterable__catalogue_product.discount_display,
	iterable__catalogue_product.discount_tooltip,
	iterable__catalogue_product.display_order,
	iterable__catalogue_product.division_id,
	iterable__catalogue_product.division_name,
	iterable__catalogue_product.end_date_display,
	iterable__catalogue_product.has_flights_available,
	iterable__catalogue_product.has_flights_included,
	iterable__catalogue_product.hash,
	iterable__catalogue_product.hotel_details,
	iterable__catalogue_product.is_catalogue,
	iterable__catalogue_product.is_connected,
	iterable__catalogue_product.is_current,
	iterable__catalogue_product.is_deposit_sale,
	iterable__catalogue_product.is_dynamic_package,
	iterable__catalogue_product.is_editors_pick,
	iterable__catalogue_product.is_exclusive,
	iterable__catalogue_product.is_hidden_for_app,
	iterable__catalogue_product.is_hidden_for_whitelabels,
	iterable__catalogue_product.is_hotel_chain,
	iterable__catalogue_product.is_mysterious,
	iterable__catalogue_product.is_package,
	iterable__catalogue_product.is_refundable,
	iterable__catalogue_product.is_smart_stay,
	iterable__catalogue_product.is_time_limited,
	iterable__catalogue_product.is_zero_deposit,
	iterable__catalogue_product.latitude,
	iterable__catalogue_product.lead_image_url_array,
	iterable__catalogue_product.lead_image_url_with_size_array,
	iterable__catalogue_product.lead_rate_for_display,
	iterable__catalogue_product.lead_rate_label,
	iterable__catalogue_product.lead_rate_tooltip,
	iterable__catalogue_product.lead_rate_unit,
	iterable__catalogue_product.lead_rate_unit_label,
	iterable__catalogue_product.lead_rate_unit_per_person,
	iterable__catalogue_product.links_price_comparison,
	iterable__catalogue_product.links_sale,
	iterable__catalogue_product.links_trip_advisor,
	iterable__catalogue_product.longitude,
	iterable__catalogue_product.main_paragraph,
	iterable__catalogue_product.max_number_of_adults,
	iterable__catalogue_product.month_availability,
	iterable__catalogue_product.number_of_hotel_nights,
	iterable__catalogue_product.offer_ids,
	iterable__catalogue_product.photos,
	iterable__catalogue_product.pricing_model_for_display,
	iterable__catalogue_product.promotion,
	iterable__catalogue_product.rack_rate_for_display,
	iterable__catalogue_product.rack_rate_unit,
	iterable__catalogue_product.rack_rate_unit_per_person,
	iterable__catalogue_product.reason_to_love,
	iterable__catalogue_product.record,
	iterable__catalogue_product.room_description,
	iterable__catalogue_product.row_hash,
	iterable__catalogue_product.sale_active,
	iterable__catalogue_product.sale_url,
	iterable__catalogue_product.second_opinion,
	NULL AS total_price_for_display,
	iterable__catalogue_product.show_discount,
	iterable__catalogue_product.show_prices,
	iterable__catalogue_product.show_rack_rate,
	iterable__catalogue_product.summary,
	iterable__catalogue_product.tags,
	iterable__catalogue_product.territory,
	iterable__catalogue_product.territory_id,
	iterable__catalogue_product.territory_locale,
	iterable__catalogue_product.times_booked,
	iterable__catalogue_product.title,
	iterable__catalogue_product.travel_details,
	iterable__catalogue_product.travel_type,
	iterable__catalogue_product.type,
	iterable__catalogue_product.we_like,
	iterable__catalogue_product.no_of_reviews,
	iterable__catalogue_product.average_review_score_zero_to_five,
	iterable__catalogue_product.average_review_score_zero_to_ten,
	iterable__catalogue_product.offer_inclusions_english_locale,
	iterable__catalogue_product.offer_inclusions_territory_locale,
	iterable__catalogue_product.common_offer_inclusions_english_locale,
	iterable__catalogue_product.common_offer_inclusions_territory_locale
FROM data_vault_mvp.dwh.iterable__catalogue_product
;

--swap table back in
CREATE OR REPLACE TABLE data_vault_mvp.dwh.iterable__catalogue_product CLONE data_vault_mvp.dwh.iterable__catalogue_product__temp
;

COMMIT
;
-- drop clone
DROP TABLE data_vault_mvp.dwh.iterable__catalogue_product__temp;


SELECT count(*) FROM data_vault_mvp.dwh.iterable__catalogue_product_20230726;
SELECT count(*) FROM data_vault_mvp.dwh.iterable__catalogue_product icp;

