SELECT
    e.app_id,
    e.platform,
    e.etl_tstamp,
    e.collector_tstamp,
    e.dvce_created_tstamp,
    e.event,
    e.event_id,
    e.txn_id,
    e.name_tracker,
    e.v_tracker,
    e.v_collector,
    e.v_etl,
    e.user_id,
    e.user_ipaddress,
    e.user_fingerprint,
    e.domain_userid,
    e.domain_sessionidx,
    e.network_userid,
    e.geo_country,
    e.geo_region,
    e.geo_city,
    e.geo_zipcode,
    e.geo_latitude,
    e.geo_longitude,
    e.geo_region_name,
    e.ip_isp,
    e.ip_organization,
    e.ip_domain,
    e.ip_netspeed,
    e.page_url,
    e.page_title,
    e.page_referrer,
    e.page_urlscheme,
    e.page_urlhost,
    e.page_urlport,
    e.page_urlpath,
    e.page_urlquery,
    e.page_urlfragment,
    e.refr_urlscheme,
    e.refr_urlhost,
    e.refr_urlport,
    e.refr_urlpath,
    e.refr_urlquery,
    e.refr_urlfragment,
    e.refr_medium,
    e.refr_source,
    e.refr_term,
    e.mkt_medium,
    e.mkt_source,
    e.mkt_term,
    e.mkt_content,
    e.mkt_campaign,
    e.se_category,
    e.se_action,
    e.se_label,
    e.se_property,
    e.se_value,
    e.tr_orderid,
    e.tr_affiliation,
    e.tr_total,
    e.tr_tax,
    e.tr_shipping,
    e.tr_city,
    e.tr_state,
    e.tr_country,
    e.ti_orderid,
    e.ti_sku,
    e.ti_name,
    e.ti_category,
    e.ti_price,
    e.ti_quantity,
    e.pp_xoffset_min,
    e.pp_xoffset_max,
    e.pp_yoffset_min,
    e.pp_yoffset_max,
    e.useragent,
    e.br_name,
    e.br_family,
    e.br_version,
    e.br_type,
    e.br_renderengine,
    e.br_lang,
    e.br_features_pdf,
    e.br_features_flash,
    e.br_features_java,
    e.br_features_director,
    e.br_features_quicktime,
    e.br_features_realplayer,
    e.br_features_windowsmedia,
    e.br_features_gears,
    e.br_features_silverlight,
    e.br_cookies,
    e.br_colordepth,
    e.br_viewwidth,
    e.br_viewheight,
    e.os_name,
    e.os_family,
    e.os_manufacturer,
    e.os_timezone,
    e.dvce_type,
    e.dvce_ismobile,
    e.dvce_screenwidth,
    e.dvce_screenheight,
    e.doc_charset,
    e.doc_width,
    e.doc_height,
    e.tr_currency,
    e.tr_total_base,
    e.tr_tax_base,
    e.tr_shipping_base,
    e.ti_currency,
    e.ti_price_base,
    e.base_currency,
    e.geo_timezone,
    e.mkt_clickid,
    e.mkt_network,
    e.etl_tags,
    e.dvce_sent_tstamp,
    e.refr_domain_userid,
    e.refr_dvce_tstamp,
    e.domain_sessionid,
    e.derived_tstamp,
    e.event_vendor,
    e.event_name,
    e.event_format,
    e.event_version,
    e.event_fingerprint,
    e.true_tstamp,
    e.contexts_com_optimizely_snowplow_optimizely_summary_1,
    e.contexts_com_secretescapes_all_pages_session_login_type_context_1,
    e.contexts_com_secretescapes_sale_page_context_1,
    e.contexts_com_secretescapes_user_state_context_1,
    e.contexts_com_snowplowanalytics_snowplow_ua_parser_context_1,
    e.contexts_com_snowplowanalytics_snowplow_web_page_1,
    e.contexts_org_w3_performance_timing_1,
    e.unstruct_event_com_snowplowanalytics_snowplow_link_click_1,
    e.contexts_com_optimizely_optimizelyx_summary_1,
    e.contexts_com_secretescapes_collection_context_1,
    e.contexts_com_secretescapes_filter_context_1,
    e.contexts_com_secretescapes_screen_context_1,
    e.contexts_com_snowplowanalytics_snowplow_application_background_1,
    e.contexts_com_snowplowanalytics_snowplow_application_foreground_1,
    e.contexts_com_snowplowanalytics_snowplow_client_session_1,
    e.contexts_com_snowplowanalytics_snowplow_mobile_context_1,
    e.unstruct_event_com_snowplowanalytics_snowplow_screen_view_1,
    e.unstruct_event_com_secretescapes_searched_with_refinement_event_1,
    e.contexts_com_optimizely_experiment_1,
    e.contexts_com_optimizely_state_1,
    e.contexts_com_optimizely_variation_1,
    e.contexts_com_optimizely_visitor_1,
    e.contexts_com_optimizely_visitor_audience_1,
    e.contexts_com_optimizely_visitor_dimension_1,
    e.unstruct_event_com_snowplowanalytics_mobile_screen_view_1,
    e.contexts_com_secretescapes_booking_context_1,
    e.contexts_com_secretescapes_content_context_1,
    e.contexts_com_secretescapes_environment_context_1,
    e.contexts_com_secretescapes_secret_escapes_sale_context_1,
    e.contexts_com_secretescapes_user_context_1,
    e.contexts_com_secretescapes_who_puts_product_in_front_customer_context_1,
    e.unstruct_event_com_secretescapes_booking_update_event_1,
    e.contexts_com_secretescapes_product_display_context_1,
    e.unstruct_event_com_branch_secretescapes_install_1,
    e.contexts_com_secretescapes_search_context_1,
    e.contexts_com_google_analytics_cookies_1,
    e.unstruct_event_com_snowplowanalytics_snowplow_application_error_1,
    e.contexts_com_secretescapes_content_element_interaction_context_1,
    e.contexts_com_secretescapes_content_elements_rendered_context_1,
    e.contexts_com_secretescapes_content_element_viewed_context_1,
    e.contexts_com_secretescapes_searched_with_refinement_event_1,
    e.unstruct_event_com_secretescapes_content_element_interaction_context_1,
    e.unstruct_event_com_secretescapes_content_elements_rendered_context_1,
    e.contexts_com_secretescapes_voucher_context_1,
    e.contexts_com_snowplowanalytics_mobile_application_1,
    e.contexts_com_snowplowanalytics_mobile_screen_1,
    e.contexts_com_snowplowanalytics_snowplow_gdpr_1,
    e.unstruct_event_com_snowplowanalytics_mobile_application_install_1,
    e.unstruct_event_com_branch_secretescapes_purchase_1,
    e.unstruct_event_com_secretescapes_authorisation_event_1,
    e.load_tstamp,
    e.contexts_com_snowplowanalytics_snowplow_duplicate_1,
    e.contexts_com_secretescapes_marketing_context_1,
    e.unstruct_event_com_iterable_system_webhook_1,
    e.contexts_nl_basjes_yauaa_context_1
FROM snowplow.atomic.events e;


SELECT GET_DDL('table', 'snowplow.atomic.events');


CREATE OR REPLACE TABLE events
(
    app_id                                                                  VARCHAR(16777216),
    platform                                                                VARCHAR(16777216),
    etl_tstamp                                                              TIMESTAMP_NTZ(9),
    collector_tstamp                                                        TIMESTAMP_NTZ(9)  NOT NULL,
    dvce_created_tstamp                                                     TIMESTAMP_NTZ(9),
    event                                                                   VARCHAR(16777216),
    event_id                                                                VARCHAR(16777216) NOT NULL,
    txn_id                                                                  NUMBER(38, 0),
    name_tracker                                                            VARCHAR(16777216),
    v_tracker                                                               VARCHAR(16777216),
    v_collector                                                             VARCHAR(16777216) NOT NULL,
    v_etl                                                                   VARCHAR(16777216) NOT NULL,
    user_id                                                                 VARCHAR(16777216),
    user_ipaddress                                                          VARCHAR(16777216),
    user_fingerprint                                                        VARCHAR(16777216),
    domain_userid                                                           VARCHAR(16777216),
    domain_sessionidx                                                       NUMBER(38, 0),
    network_userid                                                          VARCHAR(16777216),
    geo_country                                                             VARCHAR(16777216),
    geo_region                                                              VARCHAR(16777216),
    geo_city                                                                VARCHAR(16777216),
    geo_zipcode                                                             VARCHAR(16777216),
    geo_latitude                                                            FLOAT,
    geo_longitude                                                           FLOAT,
    geo_region_name                                                         VARCHAR(16777216),
    ip_isp                                                                  VARCHAR(16777216),
    ip_organization                                                         VARCHAR(16777216),
    ip_domain                                                               VARCHAR(16777216),
    ip_netspeed                                                             VARCHAR(16777216),
    page_url                                                                VARCHAR(16777216),
    page_title                                                              VARCHAR(16777216),
    page_referrer                                                           VARCHAR(16777216),
    page_urlscheme                                                          VARCHAR(16777216),
    page_urlhost                                                            VARCHAR(16777216),
    page_urlport                                                            NUMBER(38, 0),
    page_urlpath                                                            VARCHAR(16777216),
    page_urlquery                                                           VARCHAR(16777216),
    page_urlfragment                                                        VARCHAR(16777216),
    refr_urlscheme                                                          VARCHAR(16777216),
    refr_urlhost                                                            VARCHAR(16777216),
    refr_urlport                                                            NUMBER(38, 0),
    refr_urlpath                                                            VARCHAR(16777216),
    refr_urlquery                                                           VARCHAR(16777216),
    refr_urlfragment                                                        VARCHAR(16777216),
    refr_medium                                                             VARCHAR(16777216),
    refr_source                                                             VARCHAR(16777216),
    refr_term                                                               VARCHAR(16777216),
    mkt_medium                                                              VARCHAR(16777216),
    mkt_source                                                              VARCHAR(16777216),
    mkt_term                                                                VARCHAR(16777216),
    mkt_content                                                             VARCHAR(16777216),
    mkt_campaign                                                            VARCHAR(16777216),
    se_category                                                             VARCHAR(16777216),
    se_action                                                               VARCHAR(16777216),
    se_label                                                                VARCHAR(16777216),
    se_property                                                             VARCHAR(16777216),
    se_value                                                                FLOAT,
    tr_orderid                                                              VARCHAR(16777216),
    tr_affiliation                                                          VARCHAR(16777216),
    tr_total                                                                NUMBER(18, 2),
    tr_tax                                                                  NUMBER(18, 2),
    tr_shipping                                                             NUMBER(18, 2),
    tr_city                                                                 VARCHAR(16777216),
    tr_state                                                                VARCHAR(16777216),
    tr_country                                                              VARCHAR(16777216),
    ti_orderid                                                              VARCHAR(16777216),
    ti_sku                                                                  VARCHAR(16777216),
    ti_name                                                                 VARCHAR(16777216),
    ti_category                                                             VARCHAR(16777216),
    ti_price                                                                NUMBER(18, 2),
    ti_quantity                                                             NUMBER(38, 0),
    pp_xoffset_min                                                          NUMBER(38, 0),
    pp_xoffset_max                                                          NUMBER(38, 0),
    pp_yoffset_min                                                          NUMBER(38, 0),
    pp_yoffset_max                                                          NUMBER(38, 0),
    useragent                                                               VARCHAR(16777216),
    br_name                                                                 VARCHAR(16777216),
    br_family                                                               VARCHAR(16777216),
    br_version                                                              VARCHAR(16777216),
    br_type                                                                 VARCHAR(16777216),
    br_renderengine                                                         VARCHAR(16777216),
    br_lang                                                                 VARCHAR(16777216),
    br_features_pdf                                                         BOOLEAN,
    br_features_flash                                                       BOOLEAN,
    br_features_java                                                        BOOLEAN,
    br_features_director                                                    BOOLEAN,
    br_features_quicktime                                                   BOOLEAN,
    br_features_realplayer                                                  BOOLEAN,
    br_features_windowsmedia                                                BOOLEAN,
    br_features_gears                                                       BOOLEAN,
    br_features_silverlight                                                 BOOLEAN,
    br_cookies                                                              BOOLEAN,
    br_colordepth                                                           VARCHAR(16777216),
    br_viewwidth                                                            NUMBER(38, 0),
    br_viewheight                                                           NUMBER(38, 0),
    os_name                                                                 VARCHAR(16777216),
    os_family                                                               VARCHAR(16777216),
    os_manufacturer                                                         VARCHAR(16777216),
    os_timezone                                                             VARCHAR(16777216),
    dvce_type                                                               VARCHAR(16777216),
    dvce_ismobile                                                           BOOLEAN,
    dvce_screenwidth                                                        NUMBER(38, 0),
    dvce_screenheight                                                       NUMBER(38, 0),
    doc_charset                                                             VARCHAR(16777216),
    doc_width                                                               NUMBER(38, 0),
    doc_height                                                              NUMBER(38, 0),
    tr_currency                                                             VARCHAR(16777216),
    tr_total_base                                                           NUMBER(18, 2),
    tr_tax_base                                                             NUMBER(18, 2),
    tr_shipping_base                                                        NUMBER(18, 2),
    ti_currency                                                             VARCHAR(16777216),
    ti_price_base                                                           NUMBER(18, 2),
    base_currency                                                           VARCHAR(16777216),
    geo_timezone                                                            VARCHAR(16777216),
    mkt_clickid                                                             VARCHAR(16777216),
    mkt_network                                                             VARCHAR(16777216),
    etl_tags                                                                VARCHAR(16777216),
    dvce_sent_tstamp                                                        TIMESTAMP_NTZ(9),
    refr_domain_userid                                                      VARCHAR(16777216),
    refr_dvce_tstamp                                                        TIMESTAMP_NTZ(9),
    domain_sessionid                                                        VARCHAR(16777216),
    derived_tstamp                                                          TIMESTAMP_NTZ(9),
    event_vendor                                                            VARCHAR(16777216),
    event_name                                                              VARCHAR(16777216),
    event_format                                                            VARCHAR(16777216),
    event_version                                                           VARCHAR(16777216),
    event_fingerprint                                                       VARCHAR(16777216),
    true_tstamp                                                             TIMESTAMP_NTZ(9),
    contexts_com_optimizely_snowplow_optimizely_summary_1                   ARRAY,
    contexts_com_secretescapes_all_pages_session_login_type_context_1       ARRAY,
    contexts_com_secretescapes_sale_page_context_1                          ARRAY,
    contexts_com_secretescapes_user_state_context_1                         ARRAY,
    contexts_com_snowplowanalytics_snowplow_ua_parser_context_1             ARRAY,
    contexts_com_snowplowanalytics_snowplow_web_page_1                      ARRAY,
    contexts_org_w3_performance_timing_1                                    ARRAY,
    unstruct_event_com_snowplowanalytics_snowplow_link_click_1              OBJECT,
    contexts_com_optimizely_optimizelyx_summary_1                           ARRAY,
    contexts_com_secretescapes_collection_context_1                         ARRAY,
    contexts_com_secretescapes_filter_context_1                             ARRAY,
    contexts_com_secretescapes_screen_context_1                             ARRAY,
    contexts_com_snowplowanalytics_snowplow_application_background_1        ARRAY,
    contexts_com_snowplowanalytics_snowplow_application_foreground_1        ARRAY,
    contexts_com_snowplowanalytics_snowplow_client_session_1                ARRAY,
    contexts_com_snowplowanalytics_snowplow_mobile_context_1                ARRAY,
    unstruct_event_com_snowplowanalytics_snowplow_screen_view_1             OBJECT,
    unstruct_event_com_secretescapes_searched_with_refinement_event_1       OBJECT,
    contexts_com_optimizely_experiment_1                                    ARRAY,
    contexts_com_optimizely_state_1                                         ARRAY,
    contexts_com_optimizely_variation_1                                     ARRAY,
    contexts_com_optimizely_visitor_1                                       ARRAY,
    contexts_com_optimizely_visitor_audience_1                              ARRAY,
    contexts_com_optimizely_visitor_dimension_1                             ARRAY,
    unstruct_event_com_snowplowanalytics_mobile_screen_view_1               OBJECT,
    contexts_com_secretescapes_booking_context_1                            ARRAY,
    contexts_com_secretescapes_content_context_1                            ARRAY,
    contexts_com_secretescapes_environment_context_1                        ARRAY,
    contexts_com_secretescapes_secret_escapes_sale_context_1                ARRAY,
    contexts_com_secretescapes_user_context_1                               ARRAY,
    contexts_com_secretescapes_who_puts_product_in_front_customer_context_1 ARRAY,
    unstruct_event_com_secretescapes_booking_update_event_1                 OBJECT,
    contexts_com_secretescapes_product_display_context_1                    ARRAY,
    unstruct_event_com_branch_secretescapes_install_1                       OBJECT,
    contexts_com_secretescapes_search_context_1                             ARRAY,
    contexts_com_google_analytics_cookies_1                                 ARRAY,
    unstruct_event_com_snowplowanalytics_snowplow_application_error_1       OBJECT,
    contexts_com_secretescapes_content_element_interaction_context_1        ARRAY,
    contexts_com_secretescapes_content_elements_rendered_context_1          ARRAY,
    contexts_com_secretescapes_content_element_viewed_context_1             ARRAY,
    contexts_com_secretescapes_searched_with_refinement_event_1             ARRAY,
    unstruct_event_com_secretescapes_content_element_interaction_context_1  OBJECT,
    unstruct_event_com_secretescapes_content_elements_rendered_context_1    OBJECT,
    contexts_com_secretescapes_voucher_context_1                            ARRAY,
    contexts_com_snowplowanalytics_mobile_application_1                     ARRAY,
    contexts_com_snowplowanalytics_mobile_screen_1                          ARRAY,
    contexts_com_snowplowanalytics_snowplow_gdpr_1                          ARRAY,
    unstruct_event_com_snowplowanalytics_mobile_application_install_1       OBJECT,
    unstruct_event_com_branch_secretescapes_purchase_1                      OBJECT,
    unstruct_event_com_secretescapes_authorisation_event_1                  OBJECT,
    load_tstamp                                                             TIMESTAMP_NTZ(9),
    contexts_com_snowplowanalytics_snowplow_duplicate_1                     ARRAY,
    contexts_com_secretescapes_marketing_context_1                          ARRAY,
    unstruct_event_com_iterable_system_webhook_1                            OBJECT,
    contexts_nl_basjes_yauaa_context_1                                      ARRAY,
    CONSTRAINT event_id_pk PRIMARY KEY (event_id)
);


DROP TABLE hygiene_vault_mvp_dev_robin.snowplow.event_stream;

self_describing_task --include 'biapp/task_catalogue/staging/hygiene/snowplow/event_stream.py'  --method 'run' --start '2023-04-27 00:00:00' --end '2023-04-27 00:00:00';


SELECT
    REPLACE(app_id, 'iterable', NULL), --remove app id from iterable events to not negatively impact territory
    unstruct_event_com_iterable_system_webhook_1,
    unstruct_event_com_iterable_system_webhook_1['eventName']::VARCHAR                      AS event_name,
    unstruct_event_com_iterable_system_webhook_1['userId']::VARCHAR                         AS user_id,
    unstruct_event_com_iterable_system_webhook_1['dataFields']['messageId']::VARCHAR        AS message_id,
    unstruct_event_com_iterable_system_webhook_1['dataFields']['platformEndpoint']::VARCHAR AS device_platform
FROM hygiene_vault_mvp_dev_robin.snowplow.event_stream
WHERE unstruct_event_com_iterable_system_webhook_1 IS NOT NULL
--   AND unstruct_event_com_iterable_system_webhook_1['userId']::VARCHAR = '79347474'
ORDER BY 4;

-- can't see anything on push open that determines device platform, investigating any other fields on the send event to help identify device eg message type id

WITH modelling AS (
    SELECT
        es.unstruct_event_com_iterable_system_webhook_1,
        es.unstruct_event_com_iterable_system_webhook_1['eventName']::VARCHAR                      AS event_name,
        es.unstruct_event_com_iterable_system_webhook_1['dataFields']['platformEndpoint']::VARCHAR AS platform_endpoint,
        REGEXP_SUBSTR(es.unstruct_event_com_iterable_system_webhook_1['dataFields']['platformEndpoint']::VARCHAR,
                      'endpoint/(.*)/prod', 1, 1, 'e')                                             AS device_type,
        es.unstruct_event_com_iterable_system_webhook_1['dataFields']['channelId']::VARCHAR        AS test
    FROM hygiene_vault_mvp_dev_robin.snowplow.event_stream AS es
    WHERE es.unstruct_event_com_iterable_system_webhook_1 IS NOT NULL
      AND es.unstruct_event_com_iterable_system_webhook_1['eventName']::VARCHAR = 'pushSend'
)
SELECT
    m.device_type,
    test,
    COUNT(*)
FROM modelling m
GROUP BY 1, 2
;

-- regex
SELECT
    'arn:aws:sns:us-east-1:203113165317:endpoint/APNS/prod-project-12408-com.justbook.JustBook/b1a0238b-8b72-31bf-81f3-ee06fa579327' AS device_platform,
    REGEXP_SUBSTR(device_platform, 'endpoint/(.*)/prod', 1, 1, 'e');


-- create a dataset a lookup table that is used to enrich the device platform for push open events

WITH count_rows AS (
    SELECT
        es.event_tstamp,
        es.unstruct_event_com_iterable_system_webhook_1['eventName']::VARCHAR            AS event_name,
        REGEXP_SUBSTR(es.unstruct_event_com_iterable_system_webhook_1['dataFields']['platformEndpoint']::VARCHAR,
                      'endpoint/(.*)/prod', 1, 1, 'e')                                   AS device_type,
        unstruct_event_com_iterable_system_webhook_1['userId']::VARCHAR                  AS user_id,
        unstruct_event_com_iterable_system_webhook_1['dataFields']['messageId']::VARCHAR AS message_id,

        COUNT(*) OVER (PARTITION BY
            unstruct_event_com_iterable_system_webhook_1['userId']::VARCHAR,
            unstruct_event_com_iterable_system_webhook_1['dataFields']['messageId']::VARCHAR
            )                                                                            AS num_rows,

        es.unstruct_event_com_iterable_system_webhook_1
    FROM hygiene_vault_mvp_dev_robin.snowplow.event_stream AS es
    WHERE es.unstruct_event_com_iterable_system_webhook_1 IS NOT NULL
      AND es.unstruct_event_com_iterable_system_webhook_1['eventName']::VARCHAR = 'pushSend'
)

SELECT *
FROM count_rows cr
WHERE cr.num_rows > 1
ORDER BY cr.user_id

