CREATE OR REPLACE FUNCTION se_dev_robin.data.airline_name_from_iata_code(iata_code VARCHAR)
    RETURNS VARCHAR
    LANGUAGE SQL
AS
$$
SELECT CASE
WHEN iata_code = 'KL' THEN	'KLM'
WHEN iata_code = 'TK' THEN	'Turkish Airlines'
WHEN iata_code = 'JP' THEN	'Adria Airways'
WHEN iata_code = 'UA' THEN	'United Airlines'
WHEN iata_code = 'EI' THEN	'Aer Lingus'
WHEN iata_code = 'KQ' THEN	'Kenya Airways'
WHEN iata_code = 'VN' THEN	'Vietnam Airlines'
WHEN iata_code = 'EN' THEN	'Air Dolomiti'
WHEN iata_code = 'AA' THEN	'American Airlines'
WHEN iata_code = 'EW' THEN	'Eurowings'
WHEN iata_code = 'EY' THEN	'Etihad Airways'
WHEN iata_code = 'ET' THEN	'Ethiopian Airlines'
WHEN iata_code = 'X3' THEN	'Hapag-Lloyd Express'
WHEN iata_code = 'KM' THEN	'Air Malta'
WHEN iata_code = 'VS' THEN	'Virgin Atlantic'
WHEN iata_code = 'HR' THEN	'Hahn Air'
WHEN iata_code = 'EK' THEN	'Emirates Airlines'
WHEN iata_code = 'W6' THEN	'Wizz Air'
WHEN iata_code = 'UX' THEN	'Air Europa'
WHEN iata_code = 'IB' THEN	'Iberia Airlines'
WHEN iata_code = 'W9' THEN	'Abelag Aviation'
WHEN iata_code = 'KE' THEN	'Korean Air'
WHEN iata_code = 'BA' THEN	'British Airways'
WHEN iata_code = 'TB' THEN	'TUI fly Belgium'
WHEN iata_code = 'LH' THEN	'Lufthansa'
WHEN iata_code = 'TP' THEN	'TAP Portugal'
WHEN iata_code = 'CI' THEN	'China Airlines'
WHEN iata_code = 'LX' THEN	'Swiss International Air Lines'
WHEN iata_code = 'TG' THEN	'Thai Airways International'
WHEN iata_code = 'OS' THEN	'Austrian Airlines'
WHEN iata_code = 'DL' THEN	'Delta Air Lines'
WHEN iata_code = 'LA' THEN	'LATAM Chile'
WHEN iata_code = 'MH' THEN	'MASwings'
WHEN iata_code = 'MK' THEN	'Air Mauritius'
WHEN iata_code = 'AC' THEN	'Air Canada'
WHEN iata_code = 'CZ' THEN	'China Southern Airlines'
WHEN iata_code = 'SA' THEN	'South African Airways'
WHEN iata_code = 'WY' THEN	'Oman Air'
WHEN iata_code = 'A3' THEN	'Aegean Airlines'
WHEN iata_code = 'SN' THEN	'Brussels International Airlines'
WHEN iata_code = 'SQ' THEN	'Singapore Airlines'
WHEN iata_code = 'CX' THEN	'Cathay Pacific'
WHEN iata_code = 'XQ' THEN	'SunExpress'
WHEN iata_code = 'DE' THEN	'Condor Flugdienst'
WHEN iata_code = 'AT' THEN	'Royal Air Maroc'
WHEN iata_code = 'OG' THEN	'Fly Play hf.'
WHEN iata_code = 'GA' THEN	'Garuda Indonesia'
WHEN iata_code = 'AF' THEN	'Air France'
WHEN iata_code = 'SK' THEN	'Scandinavian Airlines'
WHEN iata_code = '3O' THEN 'Air Arabia Maroc'
WHEN iata_code = 'AZ' THEN	'Alitalia'
WHEN iata_code = 'CA' THEN	'Air China'
WHEN iata_code = 'OU' THEN	'COURTLINE'
WHEN iata_code = 'OK' THEN	'Czech Airlines'
WHEN iata_code = 'BY' THEN	'TUI Airways'
WHEN iata_code = 'QF' THEN	'Eastern Australia Airlines'
WHEN iata_code = 'BR' THEN	'EVA Air'
WHEN iata_code = 'BT' THEN	'Air Baltic'
WHEN iata_code = 'GF' THEN	'Gulf Air'
WHEN iata_code = 'AV' THEN	'Avianca'
WHEN iata_code = 'LS' THEN	'Jet2.com'
WHEN iata_code = 'AY' THEN	'Finnair'
WHEN iata_code = 'FI' THEN	'Icelandair'
WHEN iata_code = 'FR' THEN	'Ryanair'
WHEN iata_code = 'SU' THEN	'Aeroflot Russian Airlines'
WHEN iata_code = 'DY' THEN	'Norwegian Air Shuttle'
WHEN iata_code = 'LO' THEN	'LOT Polish Airlines'
WHEN iata_code = 'YM' THEN	'Montenegro Airlines'
WHEN iata_code = 'U2' THEN	'easyJet UK'
WHEN iata_code = 'RJ' THEN	'Royal Jordanian'
WHEN iata_code = 'VY' THEN	'Formosa Airlines'
WHEN iata_code = 'HV' THEN	'Transavia Holland'
WHEN iata_code = 'GQ' THEN	'Big Sky Airlines'
WHEN iata_code = 'BE' THEN	'Flybe'
WHEN iata_code = 'UL' THEN	'SriLankan Airlines'
WHEN iata_code = 'QR' THEN	'Qatar Airways'
WHEN iata_code = 'S4' THEN	'SATA International'
WHEN iata_code = 'XC' THEN	'Corendon Airlines'
    END AS airline_name
$$

SELECT se_dev_robin.data.airline_name_from_iata_code('RJ')

self_describing_task --include 'se/data/udfs/udf_functions.py'  --method 'run' --start '2022-03-20 00:00:00' --end '2022-03-20 00:00:00'